var searchData=
[
  ['pain_20to_20specify_20the_20actions_20gmock_20sucks_0',['My mock object needs to do complex stuff. It&apos;s a lot of pain to specify the actions. gMock sucks!',['../md_googletest_2docs_2gmock__faq.html#autotoc_md198',1,'']]],
  ['pairofrange_1',['PairOfRange',['../classgnuplotio_1_1_pair_of_range.html',1,'gnuplotio']]],
  ['panic_2',['I got a warning &quot;Uninteresting function call encountered - default action taken..&quot; Should I panic?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md199',1,'']]],
  ['paramconvertergenerator_3',['ParamConverterGenerator',['../classtesting_1_1internal_1_1_param_converter_generator.html',1,'testing::internal']]],
  ['parameter_20in_20an_20action_4',['Restricting the Type of an Argument or Parameter in an ACTION',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md179',1,'']]],
  ['parameter_20why_5',['MSVC gives me warning C4301 or C4373 when I define a mock method with a const parameter. Why?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md187',1,'']]],
  ['parameterized_20abstract_20tests_6',['Creating Value-Parameterized Abstract Tests',['../md_googletest_2docs_2advanced.html#autotoc_md47',1,'']]],
  ['parameterized_20actions_7',['Legacy macro-based parameterized Actions',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md178',1,'']]],
  ['parameterized_20matchers_20quickly_8',['Writing New Parameterized Matchers Quickly',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md172',1,'']]],
  ['parameterized_20test_20parameters_9',['Specifying Names for Value-Parameterized Test Parameters',['../md_googletest_2docs_2advanced.html#autotoc_md48',1,'']]],
  ['parameterized_20tests_10',['Parameterized Tests',['../md_googletest_2docs_2advanced.html#autotoc_md46',1,'How to Write Value-Parameterized Tests'],['../md_googletest_2docs_2advanced.html#autotoc_md50',1,'Type-Parameterized Tests'],['../md_googletest_2docs_2advanced.html#autotoc_md45',1,'Value-Parameterized Tests']]],
  ['parameterized_20tests_11',['I need to test that different implementations of an interface satisfy some common requirements. Should I use typed tests or value-parameterized tests?',['../md_googletest_2docs_2faq.html#autotoc_md85',1,'']]],
  ['parameterizeddeathtest_12',['ParameterizedDeathTest',['../class_parameterized_death_test.html',1,'']]],
  ['parameterizedderivedtest_13',['ParameterizedDerivedTest',['../class_parameterized_derived_test.html',1,'']]],
  ['parameterizedtestfactory_14',['ParameterizedTestFactory',['../classtesting_1_1internal_1_1_parameterized_test_factory.html',1,'testing::internal']]],
  ['parameterizedtestsuiteinfo_15',['ParameterizedTestSuiteInfo',['../classtesting_1_1internal_1_1_parameterized_test_suite_info.html',1,'testing::internal']]],
  ['parameterizedtestsuiteinfobase_16',['ParameterizedTestSuiteInfoBase',['../classtesting_1_1internal_1_1_parameterized_test_suite_info_base.html',1,'testing::internal']]],
  ['parameterizedtestsuiteregistry_17',['ParameterizedTestSuiteRegistry',['../classtesting_1_1internal_1_1_parameterized_test_suite_registry.html',1,'testing::internal']]],
  ['parameters_18',['Specifying Names for Value-Parameterized Test Parameters',['../md_googletest_2docs_2advanced.html#autotoc_md48',1,'']]],
  ['paramgenerator_19',['ParamGenerator',['../classtesting_1_1internal_1_1_param_generator.html',1,'testing::internal']]],
  ['paramgenerator_3c_20from_20_3e_20',['ParamGenerator&lt; From &gt;',['../classtesting_1_1internal_1_1_param_generator.html',1,'testing::internal']]],
  ['paramgenerator_3c_20gen_20_3e_21',['ParamGenerator&lt; Gen &gt;',['../classtesting_1_1internal_1_1_param_generator.html',1,'testing::internal']]],
  ['paramgeneratorconverter_22',['ParamGeneratorConverter',['../classtesting_1_1internal_1_1_param_generator_converter.html',1,'testing::internal']]],
  ['paramgeneratorinterface_23',['ParamGeneratorInterface',['../classtesting_1_1internal_1_1_param_generator_interface.html',1,'testing::internal']]],
  ['paramgeneratorinterface_3c_20paramtype_20_3e_24',['ParamGeneratorInterface&lt; ParamType &gt;',['../classtesting_1_1internal_1_1_param_generator_interface.html',1,'testing::internal']]],
  ['paramgeneratorinterface_3c_20testing_3a_3ainternal_3a_3ato_20_3e_25',['ParamGeneratorInterface&lt; testing::internal::To &gt;',['../classtesting_1_1internal_1_1_param_generator_interface.html',1,'testing::internal']]],
  ['paramgeneratorinterface_3c_20to_20_3e_26',['ParamGeneratorInterface&lt; To &gt;',['../classtesting_1_1internal_1_1_param_generator_interface.html',1,'testing::internal']]],
  ['paramgeneratorinterface_3c_3a_3astd_3a_3atuple_3c_20t_2e_2e_2e_20_3e_20_3e_27',['ParamGeneratorInterface&lt;::std::tuple&lt; T... &gt; &gt;',['../classtesting_1_1internal_1_1_param_generator_interface.html',1,'testing::internal']]],
  ['paramiterator_28',['ParamIterator',['../classtesting_1_1internal_1_1_param_iterator.html',1,'testing::internal']]],
  ['paramiterator_3c_20from_20_3e_29',['ParamIterator&lt; From &gt;',['../classtesting_1_1internal_1_1_param_iterator.html',1,'testing::internal']]],
  ['paramiteratorinterface_30',['ParamIteratorInterface',['../classtesting_1_1internal_1_1_param_iterator_interface.html',1,'testing::internal']]],
  ['paramiteratorinterface_3c_20paramtype_20_3e_31',['ParamIteratorInterface&lt; ParamType &gt;',['../classtesting_1_1internal_1_1_param_iterator_interface.html',1,'testing::internal']]],
  ['paramiteratorinterface_3c_20to_20_3e_32',['ParamIteratorInterface&lt; To &gt;',['../classtesting_1_1internal_1_1_param_iterator_interface.html',1,'testing::internal']]],
  ['paramtest_33',['ParamTest',['../class_param_test.html',1,'']]],
  ['parent_20class_34',['Delegating Calls to a Parent Class',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md127',1,'']]],
  ['parentclass_35',['ParentClass',['../class_parent_class.html',1,'']]],
  ['parse_36',['parse',['../class_parser.html#a580a2a477d66684c7f061bd710409dda',1,'Parser']]],
  ['parse_5ftree_2ehh_37',['parse_tree.hh',['../parse__tree_8hh.html',1,'']]],
  ['parseflagstest_38',['ParseFlagsTest',['../classtesting_1_1_parse_flags_test.html',1,'testing']]],
  ['parser_39',['Parser',['../class_parser.html',1,'Parser&lt; InputType, OutputType &gt;'],['../class_parser.html#a1a60370aecc2259b45f0694bac10b249',1,'Parser::Parser()']]],
  ['partially_20ordered_20calls_40',['Expecting Partially Ordered Calls',['../md_googletest_2docs_2gmock__cook__book.html#PartialOrder',1,'']]],
  ['particular_20expectation_20is_20not_20satisfied_20isn_20t_20this_20redundant_41',['I have a failed test where gMock tells me TWICE that a particular expectation is not satisfied. Isn&apos;t this redundant?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md191',1,'']]],
  ['passed_20testpartresult_3a_3apassed_42',['passed {#TestPartResult::passed}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md362',1,'']]],
  ['passed_20testresult_3a_3apassed_43',['Passed {#TestResult::Passed}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md368',1,'']]],
  ['passed_20testsuite_3a_3apassed_44',['Passed {#TestSuite::Passed}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md299',1,'']]],
  ['passed_20unittest_3a_3apassed_45',['Passed {#UnitTest::Passed}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md334',1,'']]],
  ['passes_46',['Suppressing test passes',['../md_googletest_2docs_2advanced.html#autotoc_md71',1,'']]],
  ['patch_47',['Contributing A Patch',['../md_googletest_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md3',1,'']]],
  ['pathlike_48',['PathLike',['../classfoo_1_1_path_like.html',1,'foo']]],
  ['perform_20an_20arbitrary_20action_20on_20a_20mock_20function_20s_20argument_49',['How can I perform an arbitrary action on a mock function&apos;s argument?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md196',1,'']]],
  ['performing_20different_20actions_20based_20on_20the_20arguments_50',['Performing Different Actions Based on the Arguments',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md131',1,'']]],
  ['perspectives_51',['Perspectives',['../md__r_e_a_d_m_e.html#autotoc_md446',1,'Perspectives'],['../md__r_e_a_d_m_e.html#autotoc_md444',1,'TODOs and Perspectives']]],
  ['pkg_20config_20can_20t_20find_20googletest_52',['Help! pkg-config can&apos;t find GoogleTest!',['../md_googletest_2docs_2pkgconfig.html#autotoc_md223',1,'']]],
  ['pkg_20config_20in_20a_20cross_20compilation_20setting_53',['Using pkg-config in a cross-compilation setting',['../md_googletest_2docs_2pkgconfig.html#autotoc_md224',1,'']]],
  ['placement_54',['Assertion Placement',['../md_googletest_2docs_2advanced.html#autotoc_md25',1,'']]],
  ['platforms_55',['Platforms',['../md_googletest_2docs_2platforms.html',1,'Supported Platforms'],['../md_googletest_2_r_e_a_d_m_e.html#autotoc_md416',1,'Supported Platforms']]],
  ['please_20be_20friendly_56',['Please Be Friendly',['../md_googletest_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md5',1,'']]],
  ['plotdata_57',['PlotData',['../classgnuplotio_1_1_plot_data.html',1,'gnuplotio']]],
  ['plotdistribution_58',['plotDistribution',['../class_abstract_sampler.html#ac757a594d8a3a10867fc7c680e3a2c88',1,'AbstractSampler::plotDistribution()'],['../class_clt_tester.html#a5e86184185ab70de54a839cb80c06f3a',1,'CltTester::plotDistribution()']]],
  ['plotgroup_59',['PlotGroup',['../classgnuplotio_1_1_plot_group.html',1,'gnuplotio']]],
  ['plotting_5fempty_5fcontainer_60',['plotting_empty_container',['../classgnuplotio_1_1plotting__empty__container.html',1,'gnuplotio']]],
  ['plus_61',['PLUS',['../tokenizer_8hh.html#aa520fbf142ba1e7e659590c07da31921a883acd43c77567e1c3baced84ccf6ed7',1,'tokenizer.hh']]],
  ['point_20comparison_62',['Point Comparison',['../md_googletest_2docs_2advanced.html#autotoc_md19',1,'Floating-Point Comparison'],['../md_googletest_2docs_2reference_2assertions.html#floating-point',1,'Floating-Point Comparison']]],
  ['point_20matchers_63',['Floating-Point Matchers',['../md_googletest_2docs_2reference_2matchers.html#FpMatchers',1,'']]],
  ['point_20predicate_20format_20functions_64',['Floating-Point Predicate-Format Functions',['../md_googletest_2docs_2advanced.html#autotoc_md20',1,'']]],
  ['pointed_20to_20by_20a_20pointer_20argument_65',['Validating the Value Pointed to by a Pointer Argument',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md138',1,'']]],
  ['pointer_20argument_66',['Validating the Value Pointed to by a Pointer Argument',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md138',1,'']]],
  ['pointer_20matchers_67',['Pointer Matchers',['../md_googletest_2docs_2reference_2matchers.html#autotoc_md260',1,'']]],
  ['pointerprintable_68',['PointerPrintable',['../structfoo_1_1_pointer_printable.html',1,'foo']]],
  ['pointerprinter_69',['PointerPrinter',['../structtesting_1_1internal_1_1_pointer_printer.html',1,'testing::internal']]],
  ['points_70',['Points',['../md_googletest_2googlemock_2include_2gmock_2internal_2custom_2_r_e_a_d_m_e.html',1,'Customization Points'],['../md_googletest_2googletest_2include_2gtest_2internal_2custom_2_r_e_a_d_m_e.html',1,'Customization Points'],['../md_googletest_2docs_2advanced.html#autotoc_md78',1,'Turning Assertion Failures into Break-Points']]],
  ['polymorphic_20actions_71',['Writing New Polymorphic Actions',['../md_googletest_2docs_2gmock__cook__book.html#NewPolyActions',1,'']]],
  ['polymorphic_20matchers_72',['Writing New Polymorphic Matchers',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md174',1,'']]],
  ['polymorphicaction_73',['PolymorphicAction',['../classtesting_1_1_polymorphic_action.html',1,'testing']]],
  ['port_20h_20tt_74',['port h tt',['../md_googletest_2googlemock_2include_2gmock_2internal_2custom_2_r_e_a_d_m_e.html#autotoc_md381',1,'Header &lt;tt&gt;gmock-port.h&lt;/tt&gt;'],['../md_googletest_2googletest_2include_2gtest_2internal_2custom_2_r_e_a_d_m_e.html#autotoc_md389',1,'Header &lt;tt&gt;gtest-port.h&lt;/tt&gt;']]],
  ['pow_75',['POW',['../tokenizer_8hh.html#aa520fbf142ba1e7e659590c07da31921a17faf4e999b8cee4c36915c1f54ccffe',1,'tokenizer.hh']]],
  ['precalculatedprimetable_76',['PreCalculatedPrimeTable',['../class_pre_calculated_prime_table.html',1,'']]],
  ['predformatfunctor1_77',['PredFormatFunctor1',['../struct_pred_format_functor1.html',1,'']]],
  ['predformatfunctor2_78',['PredFormatFunctor2',['../struct_pred_format_functor2.html',1,'']]],
  ['predformatfunctor3_79',['PredFormatFunctor3',['../struct_pred_format_functor3.html',1,'']]],
  ['predformatfunctor4_80',['PredFormatFunctor4',['../struct_pred_format_functor4.html',1,'']]],
  ['predformatfunctor5_81',['PredFormatFunctor5',['../struct_pred_format_functor5.html',1,'']]],
  ['predfunctor1_82',['PredFunctor1',['../struct_pred_functor1.html',1,'']]],
  ['predfunctor2_83',['PredFunctor2',['../struct_pred_functor2.html',1,'']]],
  ['predfunctor3_84',['PredFunctor3',['../struct_pred_functor3.html',1,'']]],
  ['predfunctor4_85',['PredFunctor4',['../struct_pred_functor4.html',1,'']]],
  ['predfunctor5_86',['PredFunctor5',['../struct_pred_functor5.html',1,'']]],
  ['predicate_20assertions_87',['Predicate Assertions',['../md_googletest_2docs_2reference_2assertions.html#predicates',1,'']]],
  ['predicate_20assertions_20for_20better_20error_20messages_88',['Predicate Assertions for Better Error Messages',['../md_googletest_2docs_2advanced.html#autotoc_md15',1,'']]],
  ['predicate_20format_20functions_89',['Floating-Point Predicate-Format Functions',['../md_googletest_2docs_2advanced.html#autotoc_md20',1,'']]],
  ['predicate_20formatter_90',['Using a Predicate-Formatter',['../md_googletest_2docs_2advanced.html#autotoc_md18',1,'']]],
  ['predicate1test_91',['Predicate1Test',['../class_predicate1_test.html',1,'']]],
  ['predicate2test_92',['Predicate2Test',['../class_predicate2_test.html',1,'']]],
  ['predicate3test_93',['Predicate3Test',['../class_predicate3_test.html',1,'']]],
  ['predicate4test_94',['Predicate4Test',['../class_predicate4_test.html',1,'']]],
  ['predicate5test_95',['Predicate5Test',['../class_predicate5_test.html',1,'']]],
  ['predicates_96',['Predicates',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md133',1,'Using Matchers as Predicates'],['../md_googletest_2docs_2reference_2matchers.html#MatchersAsPredicatesCheat',1,'Using Matchers as Predicates']]],
  ['predicates_20as_20matchers_97',['Using Predicates as Matchers',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md135',1,'']]],
  ['prefer_20test_20fixtures_20over_20global_20variables_98',['Why should I prefer test fixtures over global variables?',['../md_googletest_2docs_2faq.html#autotoc_md98',1,'']]],
  ['premature_20exit_99',['Detecting Test Premature Exit',['../md_googletest_2docs_2advanced.html#autotoc_md77',1,'']]],
  ['prerequisites_100',['Prerequisites',['../md_googletest_2docs_2quickstart-bazel.html#autotoc_md236',1,'Prerequisites'],['../md_googletest_2docs_2quickstart-cmake.html#autotoc_md241',1,'Prerequisites'],['../md__r_e_a_d_m_e.html#autotoc_md425',1,'Prerequisites']]],
  ['pretty_20tedious_101',['I have several test suites which share the same test fixture logic; do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_googletest_2docs_2faq.html#autotoc_md96',1,'']]],
  ['prettyunittestresultprinter_102',['PrettyUnitTestResultPrinter',['../classtesting_1_1internal_1_1_pretty_unit_test_result_printer.html',1,'testing::internal']]],
  ['previous_20threads_20that_20were_20already_20joined_103',['Why does ASSERT_DEATH complain about previous threads that were already joined?',['../md_googletest_2docs_2faq.html#autotoc_md101',1,'']]],
  ['primer_104',['GoogleTest Primer',['../md_googletest_2docs_2primer.html',1,'']]],
  ['primetable_105',['PrimeTable',['../class_prime_table.html',1,'']]],
  ['primitive_5ffunctions_2ehh_106',['primitive_functions.hh',['../primitive__functions_8hh.html',1,'']]],
  ['print_20your_20values_107',['Print Your Values',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md182',1,'Teaching gMock How to Print Your Values'],['../md_googletest_2docs_2advanced.html#autotoc_md27',1,'Teaching GoogleTest How to Print Your Values']]],
  ['printableviaprintto_108',['PrintableViaPrintTo',['../structfoo_1_1_printable_via_print_to.html',1,'foo']]],
  ['printableviaprinttotemplate_109',['PrintableViaPrintToTemplate',['../classfoo_1_1_printable_via_print_to_template.html',1,'foo']]],
  ['printdistribution_110',['printDistribution',['../class_abstract_sampler.html#afc110350241dd9e506f09282b1090a12',1,'AbstractSampler']]],
  ['printers_20h_20tt_111',['Header &lt;tt&gt;gtest-printers.h&lt;/tt&gt;',['../md_googletest_2googletest_2include_2gtest_2internal_2custom_2_r_e_a_d_m_e.html#autotoc_md394',1,'']]],
  ['prints_112',['Controlling How Much Information gMock Prints',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md163',1,'']]],
  ['prints_20a_20warning_20when_20a_20function_20without_20expect_5fcall_20is_20called_20even_20if_20i_20have_20set_20its_20behavior_20using_20on_5fcall_20would_20it_20be_20reasonable_20not_20to_20show_20the_20warning_20in_20this_20case_113',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md194',1,'']]],
  ['prints_20the_20log_20messages_20in_20a_20death_20test_20s_20child_20process_20only_20when_20the_20test_20fails_20how_20can_20i_20see_20the_20log_20messages_20when_20the_20death_20test_20succeeds_114',['GoogleTest prints the LOG messages in a death test&apos;s child process only when the test fails. How can I see the LOG messages when the death test succeeds?',['../md_googletest_2docs_2faq.html#autotoc_md104',1,'']]],
  ['printtostring_115',['PrintToString',['../md_googletest_2docs_2reference_2testing.html#PrintToString',1,'']]],
  ['printtostringparamname_116',['PrintToStringParamName',['../structtesting_1_1_print_to_string_param_name.html',1,'testing::PrintToStringParamName'],['../md_googletest_2docs_2reference_2testing.html#PrintToStringParamName',1,'PrintToStringParamName']]],
  ['private_20code_117',['Testing Private Code',['../md_googletest_2docs_2advanced.html#autotoc_md51',1,'']]],
  ['private_20or_20protected_20methods_118',['Mocking Private or Protected Methods',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md120',1,'']]],
  ['privatecode_119',['PrivateCode',['../class_private_code.html',1,'']]],
  ['problem_120',['When I call a method on my mock object, the method for the real object is invoked instead. What&apos;s the problem?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md185',1,'']]],
  ['process_20only_20when_20the_20test_20fails_20how_20can_20i_20see_20the_20log_20messages_20when_20the_20death_20test_20succeeds_121',['GoogleTest prints the LOG messages in a death test&apos;s child process only when the test fails. How can I see the LOG messages when the death test succeeds?',['../md_googletest_2docs_2faq.html#autotoc_md104',1,'']]],
  ['program_122',['Program',['../md__r_e_a_d_m_e.html#autotoc_md424',1,'How to Compile the Program'],['../md__r_e_a_d_m_e.html#autotoc_md430',1,'Running the Program']]],
  ['program_20crashed_20and_20tt_20scopedmocklog_20tt_20spit_20out_20tons_20of_20messages_20is_20it_20a_20gmock_20bug_123',['My program crashed and &lt;tt&gt;ScopedMockLog&lt;/tt&gt; spit out tons of messages. Is it a gMock bug?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md189',1,'']]],
  ['programmatically_124',['Registering tests programmatically',['../md_googletest_2docs_2advanced.html#autotoc_md53',1,'']]],
  ['programs_3a_20advanced_20options_125',['Running Test Programs: Advanced Options',['../md_googletest_2docs_2advanced.html#autotoc_md59',1,'']]],
  ['project_126',['Project',['../md_googletest_2googletest_2_r_e_a_d_m_e.html#autotoc_md399',1,'Incorporating Into An Existing CMake Project'],['../md_googletest_2googletest_2_r_e_a_d_m_e.html#autotoc_md398',1,'Standalone CMake Project']]],
  ['project_127',['Set up a project',['../md_googletest_2docs_2quickstart-cmake.html#autotoc_md242',1,'']]],
  ['project_20overview_128',['Project Overview',['../md__r_e_a_d_m_e.html#autotoc_md423',1,'']]],
  ['projects_129',['Related Open Source Projects',['../md_googletest_2_r_e_a_d_m_e.html#autotoc_md418',1,'']]],
  ['propagating_20fatal_20failures_130',['Propagating Fatal Failures',['../md_googletest_2docs_2advanced.html#autotoc_md38',1,'']]],
  ['propertyone_131',['PropertyOne',['../class_property_one.html',1,'']]],
  ['propertyrecordingtest_132',['PropertyRecordingTest',['../class_property_recording_test.html',1,'']]],
  ['propertytwo_133',['PropertyTwo',['../class_property_two.html',1,'']]],
  ['protected_20methods_134',['Protected Methods',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md120',1,'Mocking Private or Protected Methods'],['../md_googletest_2docs_2reference_2testing.html#Environment-protected',1,'Protected Methods'],['../md_googletest_2docs_2reference_2testing.html#Test-protected',1,'Protected Methods']]],
  ['protectedfixturemethodstest_135',['ProtectedFixtureMethodsTest',['../class_protected_fixture_methods_test.html',1,'']]],
  ['protobufprinter_136',['ProtobufPrinter',['../structtesting_1_1internal_1_1_protobuf_printer.html',1,'testing::internal']]],
  ['proxytypelist_137',['ProxyTypeList',['../structtesting_1_1internal_1_1_proxy_type_list.html',1,'testing::internal']]],
  ['ptr_20tt_138',['Why does GoogleTest support &lt;tt&gt;EXPECT_EQ(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_EQ(NULL, ptr)&lt;/tt&gt; but not &lt;tt&gt;EXPECT_NE(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_NE(NULL, ptr)&lt;/tt&gt;?',['../md_googletest_2docs_2faq.html#autotoc_md84',1,'']]],
  ['ptr_20tt_20and_20tt_20assert_5feq_20null_20ptr_20tt_20but_20not_20tt_20expect_5fne_20null_20ptr_20tt_20and_20tt_20assert_5fne_20null_20ptr_20tt_139',['Why does GoogleTest support &lt;tt&gt;EXPECT_EQ(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_EQ(NULL, ptr)&lt;/tt&gt; but not &lt;tt&gt;EXPECT_NE(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_NE(NULL, ptr)&lt;/tt&gt;?',['../md_googletest_2docs_2faq.html#autotoc_md84',1,'']]],
  ['ptr_20tt_20and_20tt_20assert_5fne_20null_20ptr_20tt_140',['Why does GoogleTest support &lt;tt&gt;EXPECT_EQ(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_EQ(NULL, ptr)&lt;/tt&gt; but not &lt;tt&gt;EXPECT_NE(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_NE(NULL, ptr)&lt;/tt&gt;?',['../md_googletest_2docs_2faq.html#autotoc_md84',1,'']]],
  ['ptr_20tt_20but_20not_20tt_20expect_5fne_20null_20ptr_20tt_20and_20tt_20assert_5fne_20null_20ptr_20tt_141',['Why does GoogleTest support &lt;tt&gt;EXPECT_EQ(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_EQ(NULL, ptr)&lt;/tt&gt; but not &lt;tt&gt;EXPECT_NE(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_NE(NULL, ptr)&lt;/tt&gt;?',['../md_googletest_2docs_2faq.html#autotoc_md84',1,'']]],
  ['public_20methods_142',['Public Methods',['../md_googletest_2docs_2reference_2testing.html#Test-public',1,'Public Methods'],['../md_googletest_2docs_2reference_2testing.html#TestSuite-public',1,'Public Methods'],['../md_googletest_2docs_2reference_2testing.html#TestInfo-public',1,'Public Methods'],['../md_googletest_2docs_2reference_2testing.html#UnitTest-public',1,'Public Methods'],['../md_googletest_2docs_2reference_2testing.html#TestEventListener-public',1,'Public Methods'],['../md_googletest_2docs_2reference_2testing.html#TestEventListeners-public',1,'Public Methods'],['../md_googletest_2docs_2reference_2testing.html#TestPartResult-public',1,'Public Methods'],['../md_googletest_2docs_2reference_2testing.html#TestProperty-public',1,'Public Methods'],['../md_googletest_2docs_2reference_2testing.html#TestResult-public',1,'Public Methods']]],
  ['put_20it_143',['Where to Put It',['../md_googletest_2docs_2gmock__for__dummies.html#autotoc_md210',1,'']]]
];
