var searchData=
[
  ['s_20a_20lot_20of_20pain_20to_20specify_20the_20actions_20gmock_20sucks_0',['My mock object needs to do complex stuff. It&apos;s a lot of pain to specify the actions. gMock sucks!',['../md_googletest_2docs_2gmock__faq.html#autotoc_md198',1,'']]],
  ['s_20argument_1',['How can I perform an arbitrary action on a mock function&apos;s argument?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md196',1,'']]],
  ['s_20argument_20in_20an_20action_2',['How can I delete the mock function&apos;s argument in an action?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md195',1,'']]],
  ['s_20arguments_3',['Selecting an Action&apos;s Arguments',['../md_googletest_2docs_2gmock__cook__book.html#SelectingArgs',1,'']]],
  ['s_20behavior_20based_20on_20the_20state_4',['Changing a Mock Object&apos;s Behavior Based on the State',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md149',1,'']]],
  ['s_20c_20test_20framework_5',['Welcome to &lt;strong&gt;GoogleTest&lt;/strong&gt;, Google&apos;s C++ test framework!',['../md_googletest_2_r_e_a_d_m_e.html#autotoc_md413',1,'']]],
  ['s_20child_20process_20only_20when_20the_20test_20fails_20how_20can_20i_20see_20the_20log_20messages_20when_20the_20death_20test_20succeeds_6',['GoogleTest prints the LOG messages in a death test&apos;s child process only when the test fails. How can I see the LOG messages when the death test succeeds?',['../md_googletest_2docs_2faq.html#autotoc_md104',1,'']]],
  ['s_20going_20on_7',['My compiler complains that a constructor (or destructor) cannot return a value. What&apos;s going on?',['../md_googletest_2docs_2faq.html#autotoc_md94',1,'']]],
  ['s_20guide_8',['GoogleTest User&apos;s Guide',['../md_googletest_2docs_2index.html',1,'']]],
  ['s_20name_9',['Getting the Current Test&apos;s Name',['../md_googletest_2docs_2advanced.html#autotoc_md54',1,'']]],
  ['s_20result_10',['Ignoring an Action&apos;s Result',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md154',1,'']]],
  ['s_20the_20problem_11',['When I call a method on my mock object, the method for the real object is invoked instead. What&apos;s the problem?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md185',1,'']]],
  ['s_20type_12',['Using the ACTION Object&apos;s Type',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md181',1,'']]],
  ['s_20wrong_13',['The compiler complains about &quot;undefined references&quot; to some static const member variables, but I did define them in the class body. What&apos;s wrong?',['../md_googletest_2docs_2faq.html#autotoc_md88',1,'']]],
  ['said_20otherwise_14',['All Expectations Are Sticky (Unless Said Otherwise)',['../md_googletest_2docs_2gmock__for__dummies.html#StickyExpectations',1,'']]],
  ['same_20data_20configuration_20for_20multiple_20tests_15',['Test Fixtures: Using the Same Data Configuration for Multiple Tests',['../md_googletest_2docs_2primer.html#same-data-multiple-tests',1,'']]],
  ['same_20test_20fixture_20logic_20do_20i_20have_20to_20define_20a_20new_20test_20fixture_20class_20for_20each_20of_20them_20this_20seems_20pretty_20tedious_16',['I have several test suites which share the same test fixture logic; do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_googletest_2docs_2faq.html#autotoc_md96',1,'']]],
  ['same_20test_20suite_17',['Sharing Resources Between Tests in the Same Test Suite',['../md_googletest_2docs_2advanced.html#autotoc_md43',1,'']]],
  ['sample_18',['sample',['../class_abstract_sampler.html#a7bedcc63775853e2c461aea25d3312ea',1,'AbstractSampler::sample()'],['../class_normal_box_muller_sampler.html#aa5eeb799f6e08d063df49ebca103d388',1,'NormalBoxMullerSampler::sample()'],['../class_normal_inverse_sampler.html#a5a125b33494e8a2305d358d188452bc1',1,'NormalInverseSampler::sample()'],['../class_uniform_sampler.html#ae352adfceb12d692f021df61b48c317c',1,'UniformSampler::sample()']]],
  ['samples_19',['Googletest Samples',['../md_googletest_2docs_2samples.html',1,'']]],
  ['sampling_20module_20',['Sampling Module',['../md__r_e_a_d_m_e.html#autotoc_md435',1,'']]],
  ['sampling_2ehh_21',['sampling.hh',['../sampling_8hh.html',1,'']]],
  ['sanitizer_20integration_22',['Sanitizer Integration',['../md_googletest_2docs_2advanced.html#autotoc_md80',1,'']]],
  ['satisfied_20isn_20t_20this_20redundant_23',['I have a failed test where gMock tells me TWICE that a particular expectation is not satisfied. Isn&apos;t this redundant?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md191',1,'']]],
  ['satisfied_20what_20should_20i_20do_24',['I can&apos;t figure out why gMock thinks my expectations are not satisfied. What should I do?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md188',1,'']]],
  ['satisfy_20some_20common_20requirements_20should_20i_20use_20typed_20tests_20or_20value_20parameterized_20tests_25',['I need to test that different implementations of an interface satisfy some common requirements. Should I use typed tests or value-parameterized tests?',['../md_googletest_2docs_2faq.html#autotoc_md85',1,'']]],
  ['saveargaction_26',['SaveArgAction',['../structtesting_1_1internal_1_1_save_arg_action.html',1,'testing::internal']]],
  ['saveargpointeeaction_27',['SaveArgPointeeAction',['../structtesting_1_1internal_1_1_save_arg_pointee_action.html',1,'testing::internal']]],
  ['scoped_5ftrace_28',['SCOPED_TRACE',['../md_googletest_2docs_2reference_2testing.html#SCOPED_TRACE',1,'']]],
  ['scopedmocklog_20tt_20spit_20out_20tons_20of_20messages_20is_20it_20a_20gmock_20bug_29',['My program crashed and &lt;tt&gt;ScopedMockLog&lt;/tt&gt; spit out tons of messages. Is it a gMock bug?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md189',1,'']]],
  ['scopedtrace_30',['ScopedTrace',['../classtesting_1_1_scoped_trace.html',1,'testing::ScopedTrace'],['../md_googletest_2docs_2reference_2testing.html#ScopedTrace',1,'ScopedTrace']]],
  ['secret_31',['Secret',['../classtesting_1_1internal_1_1_secret.html',1,'testing::internal']]],
  ['see_20the_20log_20messages_20when_20the_20death_20test_20succeeds_32',['GoogleTest prints the LOG messages in a death test&apos;s child process only when the test fails. How can I see the LOG messages when the death test succeeds?',['../md_googletest_2docs_2faq.html#autotoc_md104',1,'']]],
  ['seed_5f_33',['seed_',['../class_normal_sampler.html#a394190110f8376c741c8f0760305da55',1,'NormalSampler']]],
  ['seems_20lost_20after_20the_20death_20test_20finishes_20why_34',['My death test modifies some state, but the change seems lost after the death test finishes. Why?',['../md_googletest_2docs_2faq.html#autotoc_md86',1,'']]],
  ['seems_20pretty_20tedious_35',['I have several test suites which share the same test fixture logic; do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_googletest_2docs_2faq.html#autotoc_md96',1,'']]],
  ['seg_20faults_20how_20do_20i_20fix_20it_36',['My death test hangs (or seg-faults). How do I fix it?',['../md_googletest_2docs_2faq.html#autotoc_md91',1,'']]],
  ['selecting_20an_20action_20s_20arguments_37',['Selecting an Action&apos;s Arguments',['../md_googletest_2docs_2gmock__cook__book.html#SelectingArgs',1,'']]],
  ['selecting_20between_20overloaded_20functions_38',['Selecting Between Overloaded Functions',['../md_googletest_2docs_2gmock__cook__book.html#SelectOverload',1,'']]],
  ['selecting_20tests_39',['Selecting Tests',['../md_googletest_2docs_2advanced.html#autotoc_md60',1,'']]],
  ['separate_20tt_20test_20foo_20bar_20tt_20test_20methods_20defined_20in_20different_20namespaces_40',['Is it OK if I have two separate &lt;tt&gt;TEST(Foo, Bar)&lt;/tt&gt; test methods defined in different namespaces?',['../md_googletest_2docs_2faq.html#autotoc_md109',1,'']]],
  ['separateinstancetest_41',['SeparateInstanceTest',['../class_separate_instance_test.html',1,'']]],
  ['sequence_42',['Sequence',['../md_googletest_2docs_2reference_2mocking.html#Sequence',1,'']]],
  ['sequencetestinglistener_43',['SequenceTestingListener',['../class_sequence_testing_listener.html',1,'']]],
  ['set_20its_20behavior_20using_20on_5fcall_20would_20it_20be_20reasonable_20not_20to_20show_20the_20warning_20in_20this_20case_44',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md194',1,'']]],
  ['set_20up_20a_20bazel_20workspace_45',['Set up a Bazel workspace',['../md_googletest_2docs_2quickstart-bazel.html#autotoc_md237',1,'']]],
  ['set_20up_20a_20project_46',['Set up a project',['../md_googletest_2docs_2quickstart-cmake.html#autotoc_md242',1,'']]],
  ['set_20up_20and_20tear_20down_47',['Global Set-Up and Tear-Down',['../md_googletest_2docs_2advanced.html#autotoc_md44',1,'']]],
  ['setargpointee_20in_20willonce_20but_20gcc_20complains_20about_20conflicting_20return_20type_20specified_20what_20does_20it_20mean_48',['I use SetArgPointee() in WillOnce(), but gcc complains about &quot;conflicting return type specified&quot;. What does it mean?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md201',1,'']]],
  ['setargrefereeaction_49',['SetArgRefereeAction',['../structtesting_1_1internal_1_1_set_arg_referee_action.html',1,'testing::internal']]],
  ['setargumentpointeeaction_50',['SetArgumentPointeeAction',['../structtesting_1_1internal_1_1_set_argument_pointee_action.html',1,'testing::internal']]],
  ['setarrayargumentaction_51',['SetArrayArgumentAction',['../structtesting_1_1internal_1_1_set_array_argument_action.html',1,'testing::internal']]],
  ['setdata_52',['setData',['../class_statistics.html#a934177ba3097bfe735282560a7020153',1,'Statistics']]],
  ['setenvvar_53',['SetEnvVar',['../namespacegtest__test__utils.html#abece99ff6c6b9c882ab12c15793898bf',1,'gtest_test_utils']]],
  ['seterrnoandreturnaction_54',['SetErrnoAndReturnAction',['../classtesting_1_1internal_1_1_set_errno_and_return_action.html',1,'testing::internal']]],
  ['setting_55',['Using pkg-config in a cross-compilation setting',['../md_googletest_2docs_2pkgconfig.html#autotoc_md224',1,'']]],
  ['setting_20default_20actions_56',['Setting Default Actions',['../md_googletest_2docs_2gmock__cheat__sheet.html#OnCall',1,'']]],
  ['setting_20expectations_57',['Setting Expectations',['../md_googletest_2docs_2gmock__cheat__sheet.html#ExpectCall',1,'Setting Expectations'],['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md141',1,'Setting Expectations'],['../md_googletest_2docs_2gmock__for__dummies.html#autotoc_md213',1,'Setting Expectations']]],
  ['setting_20the_20default_20actions_20for_20a_20mock_20method_58',['Setting the Default Actions for a Mock Method',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md150',1,'']]],
  ['setting_20the_20default_20value_20for_20a_20return_20type_59',['Setting the Default Value for a Return Type',['../md_googletest_2docs_2reference_2mocking.html#DefaultValue',1,'']]],
  ['setup_60',['Setup',['../md_googletest_2googletest_2_r_e_a_d_m_e.html#autotoc_md396',1,'']]],
  ['setup_61',['setUp',['../classgoogletest-filter-unittest_1_1_g_test_filter_unit_test.html#a80e82b6c777fbbf575ad83cb8d2ae56c',1,'googletest-filter-unittest::GTestFilterUnitTest']]],
  ['setup_20environment_3a_3asetup_62',['SetUp {#Environment::SetUp}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md277',1,'']]],
  ['setup_20function_20is_20not_20called_20why_63',['My SetUp() function is not called. Why?',['../md_googletest_2docs_2faq.html#autotoc_md95',1,'']]],
  ['setup_20teardown_64',['Should I use the constructor/destructor of the test fixture or SetUp()/TearDown()?',['../md_googletest_2docs_2faq.html#CtorVsSetUp',1,'']]],
  ['setup_20test_3a_3asetup_65',['SetUp {#Test::SetUp}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md286',1,'']]],
  ['setupenvironment_66',['SetupEnvironment',['../class_setup_environment.html',1,'']]],
  ['setupfailtest_67',['SetupFailTest',['../class_setup_fail_test.html',1,'']]],
  ['setuptestcasetest_68',['SetUpTestCaseTest',['../classtesting_1_1_set_up_test_case_test.html',1,'testing']]],
  ['setuptestsuite_20test_3a_3asetuptestsuite_69',['SetUpTestSuite {#Test::SetUpTestSuite}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md279',1,'']]],
  ['setuptestsuitetest_70',['SetUpTestSuiteTest',['../classtesting_1_1_set_up_test_suite_test.html',1,'testing']]],
  ['setvalue_71',['SetValue',['../md_googletest_2docs_2reference_2testing.html#SetValue',1,'']]],
  ['several_20test_20suites_20which_20share_20the_20same_20test_20fixture_20logic_20do_20i_20have_20to_20define_20a_20new_20test_20fixture_20class_20for_20each_20of_20them_20this_20seems_20pretty_20tedious_72',['I have several test suites which share the same test fixture logic; do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_googletest_2docs_2faq.html#autotoc_md96',1,'']]],
  ['share_20the_20same_20test_20fixture_20logic_20do_20i_20have_20to_20define_20a_20new_20test_20fixture_20class_20for_20each_20of_20them_20this_20seems_20pretty_20tedious_73',['I have several test suites which share the same test fixture logic; do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_googletest_2docs_2faq.html#autotoc_md96',1,'']]],
  ['shared_20library_20dll_74',['As a Shared Library (DLL)',['../md_googletest_2googletest_2_r_e_a_d_m_e.html#autotoc_md404',1,'']]],
  ['sharing_20actions_75',['Sharing Actions',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md156',1,'']]],
  ['sharing_20matchers_76',['Sharing Matchers',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md140',1,'']]],
  ['sharing_20resources_20between_20tests_20in_20the_20same_20test_20suite_77',['Sharing Resources Between Tests in the Same Test Suite',['../md_googletest_2docs_2advanced.html#autotoc_md43',1,'']]],
  ['sheet_78',['gMock Cheat Sheet',['../md_googletest_2docs_2gmock__cheat__sheet.html',1,'']]],
  ['should_20i_20do_79',['I can&apos;t figure out why gMock thinks my expectations are not satisfied. What should I do?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md188',1,'']]],
  ['should_20i_20panic_80',['I got a warning &quot;Uninteresting function call encountered - default action taken..&quot; Should I panic?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md199',1,'']]],
  ['should_20i_20prefer_20test_20fixtures_20over_20global_20variables_81',['Why should I prefer test fixtures over global variables?',['../md_googletest_2docs_2faq.html#autotoc_md98',1,'']]],
  ['should_20i_20use_20invoke_20or_20implement_20the_20actioninterface_20interface_82',['I want to define a custom action. Should I use Invoke() or implement the ActionInterface interface?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md200',1,'']]],
  ['should_20i_20use_20the_20constructor_20destructor_20of_20the_20test_20fixture_20or_20setup_20teardown_83',['Should I use the constructor/destructor of the test fixture or SetUp()/TearDown()?',['../md_googletest_2docs_2faq.html#CtorVsSetUp',1,'']]],
  ['should_20i_20use_20typed_20tests_20or_20value_20parameterized_20tests_84',['I need to test that different implementations of an interface satisfy some common requirements. Should I use typed tests or value-parameterized tests?',['../md_googletest_2docs_2faq.html#autotoc_md85',1,'']]],
  ['should_20it_20do_85',['Actions: What Should It Do?',['../md_googletest_2docs_2gmock__for__dummies.html#autotoc_md217',1,'']]],
  ['should_20test_20suite_20names_20and_20test_20names_20not_20contain_20underscore_86',['Why should test suite names and test names not contain underscore?',['../md_googletest_2docs_2faq.html#autotoc_md83',1,'']]],
  ['should_5frun_20testinfo_3a_3ashould_5frun_87',['should_run {#TestInfo::should_run}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md312',1,'']]],
  ['should_5frun_20testsuite_3a_3ashould_5frun_88',['should_run {#TestSuite::should_run}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md290',1,'']]],
  ['show_20the_20warning_20in_20this_20case_89',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md194',1,'']]],
  ['shuffling_20the_20tests_90',['Shuffling the Tests',['../md_googletest_2docs_2advanced.html#autotoc_md67',1,'']]],
  ['side_20effects_91',['Side Effects',['../md_googletest_2docs_2gmock__cook__book.html#MockingSideEffects',1,'Mocking Side Effects'],['../md_googletest_2docs_2reference_2actions.html#autotoc_md247',1,'Side Effects']]],
  ['side_20effects_92',['Matchers must have no side-effects',['../md_googletest_2docs_2gmock__cook__book.html#PureMatchers',1,'']]],
  ['sigma_5f_93',['sigma_',['../class_normal_sampler.html#a5bc92829447251d63c2dc2eeacc57618',1,'NormalSampler']]],
  ['simple_20matchers_94',['Using Simple Matchers',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md130',1,'']]],
  ['simple_20tests_95',['Simple Tests',['../md_googletest_2docs_2primer.html#autotoc_md231',1,'']]],
  ['simplifying_20the_20interface_20without_20breaking_20existing_20code_96',['Simplifying the Interface without Breaking Existing Code',['../md_googletest_2docs_2gmock__cook__book.html#SimplerInterfaces',1,'']]],
  ['skipentireenvironmenttest_97',['SkipEntireEnvironmentTest',['../classgtest__skip__check__output__test_1_1_skip_entire_environment_test.html',1,'gtest_skip_check_output_test.SkipEntireEnvironmentTest'],['../classgtest__skip__environment__check__output__test_1_1_skip_entire_environment_test.html',1,'gtest_skip_environment_check_output_test.SkipEntireEnvironmentTest']]],
  ['skipped_20testpartresult_3a_3askipped_98',['skipped {#TestPartResult::skipped}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md361',1,'']]],
  ['skipped_20testresult_3a_3askipped_99',['Skipped {#TestResult::Skipped}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md369',1,'']]],
  ['skipped_5ftest_5fcount_20testsuite_3a_3askipped_5ftest_5fcount_100',['skipped_test_count {#TestSuite::skipped_test_count}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md292',1,'']]],
  ['skipped_5ftest_5fcount_20unittest_3a_3askipped_5ftest_5fcount_101',['skipped_test_count {#UnitTest::skipped_test_count}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md325',1,'']]],
  ['skippedtest_102',['SkippedTest',['../class_skipped_test.html',1,'']]],
  ['skipping_20test_20execution_103',['Skipping test execution',['../md_googletest_2docs_2advanced.html#autotoc_md26',1,'']]],
  ['some_20common_20requirements_20should_20i_20use_20typed_20tests_20or_20value_20parameterized_20tests_104',['I need to test that different implementations of an interface satisfy some common requirements. Should I use typed tests or value-parameterized tests?',['../md_googletest_2docs_2faq.html#autotoc_md85',1,'']]],
  ['some_20state_20but_20the_20change_20seems_20lost_20after_20the_20death_20test_20finishes_20why_105',['My death test modifies some state, but the change seems lost after the death test finishes. Why?',['../md_googletest_2docs_2faq.html#autotoc_md86',1,'']]],
  ['some_20static_20const_20member_20variables_20but_20i_20did_20define_20them_20in_20the_20class_20body_20what_20s_20wrong_106',['The compiler complains about &quot;undefined references&quot; to some static const member variables, but I did define them in the class body. What&apos;s wrong?',['../md_googletest_2docs_2faq.html#autotoc_md88',1,'']]],
  ['soon_107',['Coming Soon',['../md_googletest_2_r_e_a_d_m_e.html#autotoc_md412',1,'']]],
  ['source_20projects_108',['Related Open Source Projects',['../md_googletest_2_r_e_a_d_m_e.html#autotoc_md418',1,'']]],
  ['specified_20what_20does_20it_20mean_109',['I use SetArgPointee() in WillOnce(), but gcc complains about &quot;conflicting return type specified&quot;. What does it mean?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md201',1,'']]],
  ['specify_20the_20actions_20gmock_20sucks_110',['My mock object needs to do complex stuff. It&apos;s a lot of pain to specify the actions. gMock sucks!',['../md_googletest_2docs_2gmock__faq.html#autotoc_md198',1,'']]],
  ['specifying_20calling_20conventions_20for_20mock_20functions_111',['Specifying Calling Conventions for Mock Functions',['../md_googletest_2docs_2gmock__cheat__sheet.html#autotoc_md112',1,'']]],
  ['specifying_20names_20for_20value_20parameterized_20test_20parameters_112',['Specifying Names for Value-Parameterized Test Parameters',['../md_googletest_2docs_2advanced.html#autotoc_md48',1,'']]],
  ['spit_20out_20tons_20of_20messages_20is_20it_20a_20gmock_20bug_113',['My program crashed and &lt;tt&gt;ScopedMockLog&lt;/tt&gt; spit out tons of messages. Is it a gMock bug?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md189',1,'']]],
  ['stackinterface_114',['StackInterface',['../classtesting_1_1gmock__function__mocker__test_1_1_stack_interface.html',1,'testing::gmock_function_mocker_test']]],
  ['standalone_20cmake_20project_115',['Standalone CMake Project',['../md_googletest_2googletest_2_r_e_a_d_m_e.html#autotoc_md398',1,'']]],
  ['standard_20version_116',['C++ Standard Version',['../md_googletest_2googletest_2_r_e_a_d_m_e.html#autotoc_md401',1,'']]],
  ['start_5ftimestamp_20testresult_3a_3astart_5ftimestamp_117',['start_timestamp {#TestResult::start_timestamp}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md374',1,'']]],
  ['start_5ftimestamp_20testsuite_3a_3astart_5ftimestamp_118',['start_timestamp {#TestSuite::start_timestamp}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md302',1,'']]],
  ['start_5ftimestamp_20unittest_3a_3astart_5ftimestamp_119',['start_timestamp {#UnitTest::start_timestamp}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md332',1,'']]],
  ['started_120',['Started',['../md_googletest_2docs_2gmock__for__dummies.html#autotoc_md206',1,'Getting Started'],['../md_googletest_2_r_e_a_d_m_e.html#autotoc_md414',1,'Getting Started']]],
  ['state_121',['Changing a Mock Object&apos;s Behavior Based on the State',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md149',1,'']]],
  ['state_20but_20the_20change_20seems_20lost_20after_20the_20death_20test_20finishes_20why_122',['My death test modifies some state, but the change seems lost after the death test finishes. Why?',['../md_googletest_2docs_2faq.html#autotoc_md86',1,'']]],
  ['statefulnamingfunctor_123',['StatefulNamingFunctor',['../struct_stateful_naming_functor.html',1,'']]],
  ['statefulnamingtest_124',['StatefulNamingTest',['../class_stateful_naming_test.html',1,'']]],
  ['statement_20argument_20in_20assert_5fdeath_20be_125',['What can the statement argument in ASSERT_DEATH() be?',['../md_googletest_2docs_2faq.html#autotoc_md99',1,'']]],
  ['statements_20in_20matchers_126',['Using EXPECT_ Statements in Matchers',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md169',1,'']]],
  ['static_20const_20member_20variables_20but_20i_20did_20define_20them_20in_20the_20class_20body_20what_20s_20wrong_127',['The compiler complains about &quot;undefined references&quot; to some static const member variables, but I did define them in the class body. What&apos;s wrong?',['../md_googletest_2docs_2faq.html#autotoc_md88',1,'']]],
  ['static_20global_20function_20can_20i_20mock_20it_128',['My code calls a static/global function. Can I mock it?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md197',1,'']]],
  ['static_20runtimes_129',['Visual Studio Dynamic vs Static Runtimes',['../md_googletest_2googletest_2_r_e_a_d_m_e.html#autotoc_md400',1,'']]],
  ['staticasserttypeeq_130',['StaticAssertTypeEq',['../md_googletest_2docs_2reference_2testing.html#StaticAssertTypeEq',1,'']]],
  ['staticasserttypeeqtesthelper_131',['StaticAssertTypeEqTestHelper',['../class_static_assert_type_eq_test_helper.html',1,'']]],
  ['statistics_132',['Statistics',['../class_statistics.html',1,'Statistics'],['../class_statistics.html#a017f34efcc336eb14b38a999e6f18017',1,'Statistics::Statistics()']]],
  ['statistics_20module_133',['Statistics Module',['../md__r_e_a_d_m_e.html#autotoc_md436',1,'']]],
  ['statistics_20readme_134',['Monte Carlo Statistics ReadMe',['../md__r_e_a_d_m_e.html',1,'']]],
  ['statistics_2ecc_135',['statistics.cc',['../statistics_8cc.html',1,'']]],
  ['statistics_2ehh_136',['statistics.hh',['../statistics_8hh.html',1,'']]],
  ['std_3a_3afunction_137',['Mock std::function',['../md_googletest_2docs_2gmock__cook__book.html#MockFunction',1,'']]],
  ['stdtupunwinder_138',['StdTupUnwinder',['../structgnuplotio_1_1_std_tup_unwinder.html',1,'gnuplotio']]],
  ['stdtupunwinder_3c_20tuple_2c_200_20_3e_139',['StdTupUnwinder&lt; Tuple, 0 &gt;',['../structgnuplotio_1_1_std_tup_unwinder_3_01_tuple_00_010_01_4.html',1,'gnuplotio']]],
  ['steps_140',['Compilation Steps',['../md__r_e_a_d_m_e.html#autotoc_md426',1,'']]],
  ['steps_141',['steps',['../md_googletest_2docs_2quickstart-bazel.html#autotoc_md239',1,'Next steps'],['../md_googletest_2docs_2quickstart-cmake.html#autotoc_md244',1,'Next steps']]],
  ['sticky_20unless_20said_20otherwise_142',['All Expectations Are Sticky (Unless Said Otherwise)',['../md_googletest_2docs_2gmock__for__dummies.html#StickyExpectations',1,'']]],
  ['stlcontainerview_143',['StlContainerView',['../classtesting_1_1internal_1_1_stl_container_view.html',1,'testing::internal']]],
  ['stlcontainerview_3c_20_3a_3astd_3a_3atuple_3c_20elementpointer_2c_20size_20_3e_20_3e_144',['StlContainerView&lt; ::std::tuple&lt; ElementPointer, Size &gt; &gt;',['../classtesting_1_1internal_1_1_stl_container_view_3_01_1_1std_1_1tuple_3_01_element_pointer_00_01_size_01_4_01_4.html',1,'testing::internal']]],
  ['stlcontainerview_3c_20element_5bn_5d_3e_145',['StlContainerView&lt; Element[N]&gt;',['../classtesting_1_1internal_1_1_stl_container_view_3_01_element_0f_n_0e_4.html',1,'testing::internal']]],
  ['stop_20test_20execution_20upon_20first_20failure_146',['Stop test execution upon first failure',['../md_googletest_2docs_2advanced.html#autotoc_md63',1,'']]],
  ['streamableinglobal_147',['StreamableInGlobal',['../class_streamable_in_global.html',1,'']]],
  ['streamableinlocal_148',['StreamableInLocal',['../structfoo_1_1_streamable_in_local.html',1,'foo']]],
  ['streamabletemplateinfoo_149',['StreamableTemplateInFoo',['../classfoo_1_1_streamable_template_in_foo.html',1,'foo']]],
  ['streamprinter_150',['StreamPrinter',['../structtesting_1_1internal_1_1internal__stream__operator__without__lexical__name__lookup_1_1_stream_printer.html',1,'testing::internal::internal_stream_operator_without_lexical_name_lookup']]],
  ['strict_20and_20the_20naggy_151',['The Nice, the Strict, and the Naggy',['../md_googletest_2docs_2gmock__cook__book.html#NiceStrictNaggy',1,'']]],
  ['strictmock_152',['StrictMock',['../classtesting_1_1_strict_mock.html',1,'testing::StrictMock&lt; MockClass &gt;'],['../md_googletest_2docs_2reference_2mocking.html#StrictMock',1,'StrictMock']]],
  ['strictmockimpl_153',['StrictMockImpl',['../classtesting_1_1internal_1_1_strict_mock_impl.html',1,'testing::internal']]],
  ['strictmockimpl_3c_20mockclass_20_3e_154',['StrictMockImpl&lt; MockClass &gt;',['../classtesting_1_1internal_1_1_strict_mock_impl.html',1,'testing::internal']]],
  ['string_155',['String',['../classtesting_1_1internal_1_1_string.html',1,'testing::internal']]],
  ['string_20assertions_156',['More String Assertions',['../md_googletest_2docs_2advanced.html#autotoc_md22',1,'']]],
  ['string_20comparison_157',['String Comparison',['../md_googletest_2docs_2reference_2assertions.html#c-strings',1,'']]],
  ['string_20matchers_158',['String Matchers',['../md_googletest_2docs_2reference_2matchers.html#autotoc_md256',1,'']]],
  ['strong_20google_20s_20c_20test_20framework_159',['Welcome to &lt;strong&gt;GoogleTest&lt;/strong&gt;, Google&apos;s C++ test framework!',['../md_googletest_2_r_e_a_d_m_e.html#autotoc_md413',1,'']]],
  ['strong_20googletest_20strong_20google_20s_20c_20test_20framework_160',['Welcome to &lt;strong&gt;GoogleTest&lt;/strong&gt;, Google&apos;s C++ test framework!',['../md_googletest_2_r_e_a_d_m_e.html#autotoc_md413',1,'']]],
  ['studio_20dynamic_20vs_20static_20runtimes_161',['Visual Studio Dynamic vs Static Runtimes',['../md_googletest_2googletest_2_r_e_a_d_m_e.html#autotoc_md400',1,'']]],
  ['stuff_20it_20s_20a_20lot_20of_20pain_20to_20specify_20the_20actions_20gmock_20sucks_162',['My mock object needs to do complex stuff. It&apos;s a lot of pain to specify the actions. gMock sucks!',['../md_googletest_2docs_2gmock__faq.html#autotoc_md198',1,'']]],
  ['style_163',['Style',['../md_googletest_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md6',1,'']]],
  ['style_20tt_20mock_5fmethodn_20tt_20macros_164',['Old-Style &lt;tt&gt;MOCK_METHODn&lt;/tt&gt; Macros',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md124',1,'']]],
  ['styles_165',['Death Test Styles',['../md_googletest_2docs_2advanced.html#autotoc_md34',1,'']]],
  ['sub_20routines_166',['Using Assertions in Sub-routines',['../md_googletest_2docs_2advanced.html#autotoc_md36',1,'']]],
  ['submit_20your_20own_20code_167',['How to become a contributor and submit your own code',['../md_googletest_2_c_o_n_t_r_i_b_u_t_i_n_g.html',1,'']]],
  ['subprocess_168',['Subprocess',['../classgtest__test__utils_1_1_subprocess.html',1,'gtest_test_utils']]],
  ['subroutines_169',['Asserting on Subroutines',['../md_googletest_2docs_2advanced.html#autotoc_md40',1,'']]],
  ['subroutines_20with_20an_20exception_170',['Asserting on Subroutines with an exception',['../md_googletest_2docs_2advanced.html#autotoc_md39',1,'']]],
  ['subset_20of_20the_20tests_171',['Running a Subset of the Tests',['../md_googletest_2docs_2advanced.html#autotoc_md62',1,'']]],
  ['subtractfunction_172',['SubtractFunction',['../class_subtract_function.html',1,'SubtractFunction&lt; InputType, OutputType &gt;'],['../class_subtract_function.html#ad72365888e7b2c6b77eb80d29a0cff69',1,'SubtractFunction::SubtractFunction()']]],
  ['succeed_173',['SUCCEED',['../md_googletest_2docs_2reference_2assertions.html#SUCCEED',1,'']]],
  ['succeeds_174',['GoogleTest prints the LOG messages in a death test&apos;s child process only when the test fails. How can I see the LOG messages when the death test succeeds?',['../md_googletest_2docs_2faq.html#autotoc_md104',1,'']]],
  ['success_20and_20failure_175',['Success and Failure',['../md_googletest_2docs_2advanced.html#autotoc_md13',1,'Explicit Success and Failure'],['../md_googletest_2docs_2reference_2assertions.html#success-failure',1,'Explicit Success and Failure']]],
  ['successful_5ftest_5fcount_20testsuite_3a_3asuccessful_5ftest_5fcount_176',['successful_test_count {#TestSuite::successful_test_count}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md291',1,'']]],
  ['successful_5ftest_5fcount_20unittest_3a_3asuccessful_5ftest_5fcount_177',['successful_test_count {#UnitTest::successful_test_count}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md324',1,'']]],
  ['successful_5ftest_5fsuite_5fcount_20unittest_3a_3asuccessful_5ftest_5fsuite_5fcount_178',['successful_test_suite_count {#UnitTest::successful_test_suite_count}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md320',1,'']]],
  ['successfultest_179',['SuccessfulTest',['../class_successful_test.html',1,'']]],
  ['sucks_180',['My mock object needs to do complex stuff. It&apos;s a lot of pain to specify the actions. gMock sucks!',['../md_googletest_2docs_2gmock__faq.html#autotoc_md198',1,'']]],
  ['suite_181',['Sharing Resources Between Tests in the Same Test Suite',['../md_googletest_2docs_2advanced.html#autotoc_md43',1,'']]],
  ['suite_20instead_20of_20individual_20tests_20to_20be_20named_20tt_20deathtest_20tt_20when_20it_20uses_20tt_20assert_5fdeath_20tt_182',['Why does GoogleTest require the entire test suite, instead of individual tests, to be named &lt;tt&gt;*DeathTest&lt;/tt&gt; when it uses &lt;tt&gt;ASSERT_DEATH&lt;/tt&gt;?',['../md_googletest_2docs_2faq.html#autotoc_md102',1,'']]],
  ['suite_20names_20and_20test_20names_20not_20contain_20underscore_183',['Why should test suite names and test names not contain underscore?',['../md_googletest_2docs_2faq.html#autotoc_md83',1,'']]],
  ['suite_20tt_20deathtest_20tt_20when_20it_20contains_20both_20death_20tests_20and_20non_20death_20tests_20what_20do_20i_20do_184',['But I don&apos;t like calling my entire test suite &lt;tt&gt;*DeathTest&lt;/tt&gt; when it contains both death tests and non-death tests. What do I do?',['../md_googletest_2docs_2faq.html#autotoc_md103',1,'']]],
  ['suiteapiresolver_185',['SuiteApiResolver',['../structtesting_1_1internal_1_1_suite_api_resolver.html',1,'testing::internal']]],
  ['suites_20which_20share_20the_20same_20test_20fixture_20logic_20do_20i_20have_20to_20define_20a_20new_20test_20fixture_20class_20for_20each_20of_20them_20this_20seems_20pretty_20tedious_186',['I have several test suites which share the same test fixture logic; do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_googletest_2docs_2faq.html#autotoc_md96',1,'']]],
  ['summary_20testpartresult_3a_3asummary_187',['summary {#TestPartResult::summary}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md359',1,'']]],
  ['sumof5functor_188',['SumOf5Functor',['../structtesting_1_1gmock__more__actions__test_1_1_sum_of5_functor.html',1,'testing::gmock_more_actions_test']]],
  ['sumof6functor_189',['SumOf6Functor',['../structtesting_1_1gmock__more__actions__test_1_1_sum_of6_functor.html',1,'testing::gmock_more_actions_test']]],
  ['super_20vision_20into_20mock_20calls_190',['Gaining Super Vision into Mock Calls',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md164',1,'']]],
  ['support_20features_191',['Underlying library support features',['../md_googletest_2googletest_2include_2gtest_2internal_2custom_2_r_e_a_d_m_e.html#autotoc_md392',1,'']]],
  ['support_20tt_20expect_5feq_20null_20ptr_20tt_20and_20tt_20assert_5feq_20null_20ptr_20tt_20but_20not_20tt_20expect_5fne_20null_20ptr_20tt_20and_20tt_20assert_5fne_20null_20ptr_20tt_192',['Why does GoogleTest support &lt;tt&gt;EXPECT_EQ(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_EQ(NULL, ptr)&lt;/tt&gt; but not &lt;tt&gt;EXPECT_NE(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_NE(NULL, ptr)&lt;/tt&gt;?',['../md_googletest_2docs_2faq.html#autotoc_md84',1,'']]],
  ['supported_20platforms_193',['Supported Platforms',['../md_googletest_2docs_2platforms.html',1,'Supported Platforms'],['../md_googletest_2_r_e_a_d_m_e.html#autotoc_md416',1,'Supported Platforms']]],
  ['suppress_20the_20memory_20leak_20messages_20on_20windows_194',['How do I suppress the memory leak messages on Windows?',['../md_googletest_2docs_2faq.html#autotoc_md106',1,'']]],
  ['suppressing_20test_20passes_195',['Suppressing test passes',['../md_googletest_2docs_2advanced.html#autotoc_md71',1,'']]],
  ['suppressing_20the_20elapsed_20time_196',['Suppressing the Elapsed Time',['../md_googletest_2docs_2advanced.html#autotoc_md72',1,'']]],
  ['suppressing_20utf_208_20text_20output_197',['Suppressing UTF-8 Text Output',['../md_googletest_2docs_2advanced.html#autotoc_md73',1,'']]],
  ['symbols_3a_198',['Exporting API symbols:',['../md_googletest_2googletest_2include_2gtest_2internal_2custom_2_r_e_a_d_m_e.html#autotoc_md393',1,'']]],
  ['syntax_199',['Syntax',['../md_googletest_2docs_2gmock__for__dummies.html#autotoc_md214',1,'General Syntax'],['../md__r_e_a_d_m_e.html#autotoc_md432',1,'Mathematical Expression Syntax'],['../md_googletest_2docs_2advanced.html#autotoc_md31',1,'Regular Expression Syntax']]],
  ['systems_200',['Using GoogleTest from various build systems',['../md_googletest_2docs_2pkgconfig.html',1,'']]]
];
