var searchData=
[
  ['unaryfunctor_0',['UnaryFunctor',['../structtesting_1_1gmock__more__actions__test_1_1_unary_functor.html',1,'testing::gmock_more_actions_test']]],
  ['unarymoveonlyfunctor_1',['UnaryMoveOnlyFunctor',['../structtesting_1_1gmock__more__actions__test_1_1_unary_move_only_functor.html',1,'testing::gmock_more_actions_test']]],
  ['undefined_20references_20to_20some_20static_20const_20member_20variables_20but_20i_20did_20define_20them_20in_20the_20class_20body_20what_20s_20wrong_2',['The compiler complains about &quot;undefined references&quot; to some static const member variables, but I did define them in the class body. What&apos;s wrong?',['../md_googletest_2docs_2faq.html#autotoc_md88',1,'']]],
  ['underlying_20library_20support_20features_3',['Underlying library support features',['../md_googletest_2googletest_2include_2gtest_2internal_2custom_2_r_e_a_d_m_e.html#autotoc_md392',1,'']]],
  ['underscore_4',['Why should test suite names and test names not contain underscore?',['../md_googletest_2docs_2faq.html#autotoc_md83',1,'']]],
  ['understanding_20uninteresting_20vs_20unexpected_20calls_5',['Understanding Uninteresting vs Unexpected Calls',['../md_googletest_2docs_2gmock__cook__book.html#uninteresting-vs-unexpected',1,'']]],
  ['unexpected_20calls_6',['Unexpected Calls',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md143',1,'Disallowing Unexpected Calls'],['../md_googletest_2docs_2gmock__cook__book.html#uninteresting-vs-unexpected',1,'Understanding Uninteresting vs Unexpected Calls']]],
  ['uniform_5fsampler_2ecc_7',['uniform_sampler.cc',['../uniform__sampler_8cc.html',1,'']]],
  ['uniform_5fsampler_2ehh_8',['uniform_sampler.hh',['../uniform__sampler_8hh.html',1,'']]],
  ['uniform_5fsampler_5f_9',['uniform_sampler_',['../class_normal_sampler.html#a2ad34eeeb5580bd3715f74bc733c2fe8',1,'NormalSampler']]],
  ['uniformsampler_10',['UniformSampler',['../class_uniform_sampler.html',1,'UniformSampler'],['../class_uniform_sampler.html#a07de0652a0f590b39c74bb07b17cbc15',1,'UniformSampler::UniformSampler(unsigned long long j)'],['../class_uniform_sampler.html#a0b747cd02fdbdabd06f2aebb8625db50',1,'UniformSampler::UniformSampler(unsigned long long j, float a, float b)']]],
  ['uninteresting_20arguments_11',['Ignoring Uninteresting Arguments',['../md_googletest_2docs_2gmock__cook__book.html#ParameterlessExpectations',1,'']]],
  ['uninteresting_20calls_12',['Uninteresting Calls',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md142',1,'Ignoring Uninteresting Calls'],['../md_googletest_2docs_2gmock__for__dummies.html#autotoc_md218',1,'Uninteresting Calls']]],
  ['uninteresting_20function_20call_20encountered_20default_20action_20taken_20should_20i_20panic_13',['I got a warning &quot;Uninteresting function call encountered - default action taken..&quot; Should I panic?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md199',1,'']]],
  ['uninteresting_20vs_20unexpected_20calls_14',['Understanding Uninteresting vs Unexpected Calls',['../md_googletest_2docs_2gmock__cook__book.html#uninteresting-vs-unexpected',1,'']]],
  ['unittest_15',['UnitTest',['../classtesting_1_1_unit_test.html',1,'testing::UnitTest'],['../md_googletest_2docs_2reference_2testing.html#UnitTest',1,'UnitTest']]],
  ['unittest_3a_3aad_5fhoc_5ftest_5fresult_16',['ad_hoc_test_result {#UnitTest::ad_hoc_test_result}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md337',1,'']]],
  ['unittest_3a_3acurrent_5ftest_5finfo_17',['current_test_info {#UnitTest::current_test_info}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md318',1,'']]],
  ['unittest_3a_3acurrent_5ftest_5fsuite_18',['current_test_suite {#UnitTest::current_test_suite}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md317',1,'']]],
  ['unittest_3a_3adisabled_5ftest_5fcount_19',['disabled_test_count {#UnitTest::disabled_test_count}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md328',1,'']]],
  ['unittest_3a_3aelapsed_5ftime_20',['elapsed_time {#UnitTest::elapsed_time}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md333',1,'']]],
  ['unittest_3a_3afailed_21',['Failed {#UnitTest::Failed}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md335',1,'']]],
  ['unittest_3a_3afailed_5ftest_5fcount_22',['failed_test_count {#UnitTest::failed_test_count}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md326',1,'']]],
  ['unittest_3a_3afailed_5ftest_5fsuite_5fcount_23',['failed_test_suite_count {#UnitTest::failed_test_suite_count}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md321',1,'']]],
  ['unittest_3a_3agetinstance_24',['GetInstance {#UnitTest::GetInstance}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md315',1,'']]],
  ['unittest_3a_3agettestsuite_25',['GetTestSuite {#UnitTest::GetTestSuite}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md336',1,'']]],
  ['unittest_3a_3alisteners_26',['listeners {#UnitTest::listeners}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md338',1,'']]],
  ['unittest_3a_3aoriginal_5fworking_5fdir_27',['original_working_dir {#UnitTest::original_working_dir}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md316',1,'']]],
  ['unittest_3a_3apassed_28',['Passed {#UnitTest::Passed}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md334',1,'']]],
  ['unittest_3a_3arandom_5fseed_29',['random_seed {#UnitTest::random_seed}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md319',1,'']]],
  ['unittest_3a_3areportable_5fdisabled_5ftest_5fcount_30',['reportable_disabled_test_count {#UnitTest::reportable_disabled_test_count}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md327',1,'']]],
  ['unittest_3a_3areportable_5ftest_5fcount_31',['reportable_test_count {#UnitTest::reportable_test_count}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md329',1,'']]],
  ['unittest_3a_3askipped_5ftest_5fcount_32',['skipped_test_count {#UnitTest::skipped_test_count}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md325',1,'']]],
  ['unittest_3a_3astart_5ftimestamp_33',['start_timestamp {#UnitTest::start_timestamp}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md332',1,'']]],
  ['unittest_3a_3asuccessful_5ftest_5fcount_34',['successful_test_count {#UnitTest::successful_test_count}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md324',1,'']]],
  ['unittest_3a_3asuccessful_5ftest_5fsuite_5fcount_35',['successful_test_suite_count {#UnitTest::successful_test_suite_count}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md320',1,'']]],
  ['unittest_3a_3atest_5fsuite_5fto_5frun_5fcount_36',['test_suite_to_run_count {#UnitTest::test_suite_to_run_count}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md323',1,'']]],
  ['unittest_3a_3atest_5fto_5frun_5fcount_37',['test_to_run_count {#UnitTest::test_to_run_count}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md331',1,'']]],
  ['unittest_3a_3atotal_5ftest_5fcount_38',['total_test_count {#UnitTest::total_test_count}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md330',1,'']]],
  ['unittest_3a_3atotal_5ftest_5fsuite_5fcount_39',['total_test_suite_count {#UnitTest::total_test_suite_count}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md322',1,'']]],
  ['unittesthelper_40',['UnitTestHelper',['../classtesting_1_1internal_1_1_unit_test_helper.html',1,'testing::internal']]],
  ['unittestimpl_41',['UnitTestImpl',['../classtesting_1_1internal_1_1_unit_test_impl.html',1,'testing::internal']]],
  ['unittestoptions_42',['UnitTestOptions',['../classtesting_1_1internal_1_1_unit_test_options.html',1,'testing::internal']]],
  ['unittestrecordpropertytesthelper_43',['UnitTestRecordPropertyTestHelper',['../classtesting_1_1internal_1_1_unit_test_record_property_test_helper.html',1,'testing::internal']]],
  ['universalprinter_44',['UniversalPrinter',['../classtesting_1_1internal_1_1_universal_printer.html',1,'testing::internal']]],
  ['universalprinter_3c_20const_20t_20_3e_45',['UniversalPrinter&lt; const T &gt;',['../classtesting_1_1internal_1_1_universal_printer_3_01const_01_t_01_4.html',1,'testing::internal']]],
  ['universalprinter_3c_20t_20_26_20_3e_46',['UniversalPrinter&lt; T &amp; &gt;',['../classtesting_1_1internal_1_1_universal_printer_3_01_t_01_6_01_4.html',1,'testing::internal']]],
  ['universalprinter_3c_20t_5bn_5d_3e_47',['UniversalPrinter&lt; T[N]&gt;',['../classtesting_1_1internal_1_1_universal_printer_3_01_t_0f_n_0e_4.html',1,'testing::internal']]],
  ['universalprinter_3c_20wrapper_3c_20t_20_3e_20_3e_48',['UniversalPrinter&lt; Wrapper&lt; T &gt; &gt;',['../classtesting_1_1internal_1_1_universal_printer_3_01_wrapper_3_01_t_01_4_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_49',['UniversalTersePrinter',['../classtesting_1_1internal_1_1_universal_terse_printer.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20char_20_2a_20_3e_50',['UniversalTersePrinter&lt; char * &gt;',['../classtesting_1_1internal_1_1_universal_terse_printer_3_01char_01_5_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20char16_5ft_20_2a_20_3e_51',['UniversalTersePrinter&lt; char16_t * &gt;',['../classtesting_1_1internal_1_1_universal_terse_printer_3_01char16__t_01_5_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20char32_5ft_20_2a_20_3e_52',['UniversalTersePrinter&lt; char32_t * &gt;',['../classtesting_1_1internal_1_1_universal_terse_printer_3_01char32__t_01_5_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20const_20char_20_2a_20_3e_53',['UniversalTersePrinter&lt; const char * &gt;',['../classtesting_1_1internal_1_1_universal_terse_printer_3_01const_01char_01_5_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20const_20char16_5ft_20_2a_20_3e_54',['UniversalTersePrinter&lt; const char16_t * &gt;',['../classtesting_1_1internal_1_1_universal_terse_printer_3_01const_01char16__t_01_5_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20const_20char32_5ft_20_2a_20_3e_55',['UniversalTersePrinter&lt; const char32_t * &gt;',['../classtesting_1_1internal_1_1_universal_terse_printer_3_01const_01char32__t_01_5_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20std_3a_3areference_5fwrapper_3c_20t_20_3e_20_3e_56',['UniversalTersePrinter&lt; std::reference_wrapper&lt; T &gt; &gt;',['../classtesting_1_1internal_1_1_universal_terse_printer_3_01std_1_1reference__wrapper_3_01_t_01_4_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20t_20_26_20_3e_57',['UniversalTersePrinter&lt; T &amp; &gt;',['../classtesting_1_1internal_1_1_universal_terse_printer_3_01_t_01_6_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20t_5bn_5d_3e_58',['UniversalTersePrinter&lt; T[N]&gt;',['../classtesting_1_1internal_1_1_universal_terse_printer_3_01_t_0f_n_0e_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20wchar_5ft_20_2a_20_3e_59',['UniversalTersePrinter&lt; wchar_t * &gt;',['../classtesting_1_1internal_1_1_universal_terse_printer_3_01wchar__t_01_5_01_4.html',1,'testing::internal']]],
  ['unless_20said_20otherwise_60',['All Expectations Are Sticky (Unless Said Otherwise)',['../md_googletest_2docs_2gmock__for__dummies.html#StickyExpectations',1,'']]],
  ['unprintableinfoo_61',['UnprintableInFoo',['../classfoo_1_1_unprintable_in_foo.html',1,'foo']]],
  ['unprintabletemplateinglobal_62',['UnprintableTemplateInGlobal',['../class_unprintable_template_in_global.html',1,'']]],
  ['unprotected_20commas_63',['Dealing with unprotected commas',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md119',1,'']]],
  ['unstreamable_64',['Unstreamable',['../class_unstreamable.html',1,'']]],
  ['up_20a_20bazel_20workspace_65',['Set up a Bazel workspace',['../md_googletest_2docs_2quickstart-bazel.html#autotoc_md237',1,'']]],
  ['up_20a_20project_66',['Set up a project',['../md_googletest_2docs_2quickstart-cmake.html#autotoc_md242',1,'']]],
  ['up_20and_20tear_20down_67',['Global Set-Up and Tear-Down',['../md_googletest_2docs_2advanced.html#autotoc_md44',1,'']]],
  ['updates_68',['Documentation Updates',['../md_googletest_2_r_e_a_d_m_e.html#autotoc_md409',1,'']]],
  ['upon_20first_20failure_69',['Stop test execution upon first failure',['../md_googletest_2docs_2advanced.html#autotoc_md63',1,'']]],
  ['usage_20instructions_70',['Usage Instructions',['../md__r_e_a_d_m_e.html#autotoc_md429',1,'']]],
  ['use_20an_20assertion_20what_20gives_71',['The compiler complains about &amp;lsquo;no match for &apos;operator&lt;&lt;&amp;rsquo;` when I use an assertion. What gives?',['../md_googletest_2docs_2faq.html#autotoc_md105',1,'']]],
  ['use_20invoke_20or_20implement_20the_20actioninterface_20interface_72',['I want to define a custom action. Should I use Invoke() or implement the ActionInterface interface?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md200',1,'']]],
  ['use_20move_20only_20types_73',['Mocking Methods That Use Move-Only Types',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md159',1,'']]],
  ['use_20setargpointee_20in_20willonce_20but_20gcc_20complains_20about_20conflicting_20return_20type_20specified_20what_20does_20it_20mean_74',['I use SetArgPointee() in WillOnce(), but gcc complains about &quot;conflicting return type specified&quot;. What does it mean?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md201',1,'']]],
  ['use_20the_20constructor_20destructor_20of_20the_20test_20fixture_20or_20setup_20teardown_75',['Should I use the constructor/destructor of the test fixture or SetUp()/TearDown()?',['../md_googletest_2docs_2faq.html#CtorVsSetUp',1,'']]],
  ['use_20tt_20assert_5fpred_20tt_20how_20do_20i_20fix_20it_76',['The compiler complains &quot;no matching function to call&quot; when I use &lt;tt&gt;ASSERT_PRED*&lt;/tt&gt;. How do I fix it?',['../md_googletest_2docs_2faq.html#autotoc_md92',1,'']]],
  ['use_20typed_20tests_20or_20value_20parameterized_20tests_77',['I need to test that different implementations of an interface satisfy some common requirements. Should I use typed tests or value-parameterized tests?',['../md_googletest_2docs_2faq.html#autotoc_md85',1,'']]],
  ['useful_20mocks_20created_20using_20gmock_78',['Useful Mocks Created Using gMock',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md183',1,'']]],
  ['user_20s_20guide_79',['GoogleTest User&apos;s Guide',['../md_googletest_2docs_2index.html',1,'']]],
  ['userconstructortag_80',['UserConstructorTag',['../structtesting_1_1internal_1_1_do_all_action_3_01_final_action_01_4_1_1_user_constructor_tag.html',1,'testing::internal::DoAllAction&lt; FinalAction &gt;::UserConstructorTag'],['../structtesting_1_1internal_1_1_do_all_action_3_01_initial_action_00_01_other_actions_8_8_8_01_4_1_1_user_constructor_tag.html',1,'testing::internal::DoAllAction&lt; InitialAction, OtherActions... &gt;::UserConstructorTag']]],
  ['uses_20tt_20assert_5fdeath_20tt_81',['Why does GoogleTest require the entire test suite, instead of individual tests, to be named &lt;tt&gt;*DeathTest&lt;/tt&gt; when it uses &lt;tt&gt;ASSERT_DEATH&lt;/tt&gt;?',['../md_googletest_2docs_2faq.html#autotoc_md102',1,'']]],
  ['using_20a_20function_20functor_20or_20lambda_20as_20an_20action_82',['Using a Function, Functor, or Lambda as an Action',['../md_googletest_2docs_2reference_2actions.html#autotoc_md248',1,'']]],
  ['using_20a_20function_20that_20returns_20an_20assertionresult_83',['Using a Function That Returns an AssertionResult',['../md_googletest_2docs_2advanced.html#autotoc_md17',1,'']]],
  ['using_20a_20mock_20object_20but_20using_20a_20real_20object_20is_20fine_20what_20can_20be_20wrong_84',['I get a heapcheck failure when using a mock object, but using a real object is fine. What can be wrong?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md192',1,'']]],
  ['using_20a_20predicate_20formatter_85',['Using a Predicate-Formatter',['../md_googletest_2docs_2advanced.html#autotoc_md18',1,'']]],
  ['using_20a_20real_20object_20is_20fine_20what_20can_20be_20wrong_86',['I get a heapcheck failure when using a mock object, but using a real object is fine. What can be wrong?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md192',1,'']]],
  ['using_20actions_87',['Using Actions',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md145',1,'']]],
  ['using_20an_20existing_20boolean_20function_88',['Using an Existing Boolean Function',['../md_googletest_2docs_2advanced.html#autotoc_md16',1,'']]],
  ['using_20assertions_20in_20sub_20routines_89',['Using Assertions in Sub-routines',['../md_googletest_2docs_2advanced.html#autotoc_md36',1,'']]],
  ['using_20checkpoints_90',['Using Checkpoints',['../md_googletest_2docs_2gmock__cook__book.html#UsingCheckPoints',1,'']]],
  ['using_20event_20listeners_91',['Using Event Listeners',['../md_googletest_2docs_2advanced.html#autotoc_md57',1,'']]],
  ['using_20expect_5f_20statements_20in_20matchers_92',['Using EXPECT_ Statements in Matchers',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md169',1,'']]],
  ['using_20functions_20methods_20functors_20lambdas_20as_20actions_93',['Using Functions/Methods/Functors/Lambdas as Actions',['../md_googletest_2docs_2gmock__cook__book.html#FunctionsAsActions',1,'']]],
  ['using_20functions_20with_20extra_20info_20as_20actions_94',['Using Functions with Extra Info as Actions',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md151',1,'']]],
  ['using_20gmock_95',['Using gMock',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md158',1,'Misc Recipes on Using gMock'],['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md183',1,'Useful Mocks Created Using gMock']]],
  ['using_20gmock_20and_20threads_96',['Using gMock and Threads',['../md_googletest_2docs_2gmock__cook__book.html#UsingThreads',1,'']]],
  ['using_20gmock_20matchers_97',['Asserting Using gMock Matchers',['../md_googletest_2docs_2advanced.html#autotoc_md21',1,'']]],
  ['using_20googletest_98',['Who Is Using GoogleTest?',['../md_googletest_2_r_e_a_d_m_e.html#autotoc_md417',1,'']]],
  ['using_20googletest_20from_20various_20build_20systems_99',['Using GoogleTest from various build systems',['../md_googletest_2docs_2pkgconfig.html',1,'']]],
  ['using_20matchers_100',['Using Matchers',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md128',1,'']]],
  ['using_20matchers_20as_20predicates_101',['Using Matchers as Predicates',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md133',1,'Using Matchers as Predicates'],['../md_googletest_2docs_2reference_2matchers.html#MatchersAsPredicatesCheat',1,'Using Matchers as Predicates']]],
  ['using_20matchers_20in_20googletest_20assertions_102',['Using Matchers in googletest Assertions',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md134',1,'']]],
  ['using_20mocks_20in_20tests_103',['Using Mocks in Tests',['../md_googletest_2docs_2gmock__cheat__sheet.html#UsingMocks',1,'Using Mocks in Tests'],['../md_googletest_2docs_2gmock__for__dummies.html#autotoc_md211',1,'Using Mocks in Tests']]],
  ['using_20multiple_20expectations_104',['Using Multiple Expectations',['../md_googletest_2docs_2gmock__for__dummies.html#MultiExpectations',1,'']]],
  ['using_20on_5fcall_20would_20it_20be_20reasonable_20not_20to_20show_20the_20warning_20in_20this_20case_105',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md194',1,'']]],
  ['using_20pkg_20config_20in_20a_20cross_20compilation_20setting_106',['Using pkg-config in a cross-compilation setting',['../md_googletest_2docs_2pkgconfig.html#autotoc_md224',1,'']]],
  ['using_20predicates_20as_20matchers_107',['Using Predicates as Matchers',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md135',1,'']]],
  ['using_20simple_20matchers_108',['Using Simple Matchers',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md130',1,'']]],
  ['using_20the_20action_20object_20s_20type_109',['Using the ACTION Object&apos;s Type',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md181',1,'']]],
  ['using_20the_20same_20data_20configuration_20for_20multiple_20tests_110',['Test Fixtures: Using the Same Data Configuration for Multiple Tests',['../md_googletest_2docs_2primer.html#same-data-multiple-tests',1,'']]],
  ['utf_208_20text_20output_111',['Suppressing UTF-8 Text Output',['../md_googletest_2docs_2advanced.html#autotoc_md73',1,'']]]
];
