var searchData=
[
  ['object_0',['Object',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md126',1,'Delegating Calls to a Real Object'],['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md137',1,'Validating a Member of an Object']]],
  ['object_20but_20using_20a_20real_20object_20is_20fine_20what_20can_20be_20wrong_1',['I get a heapcheck failure when using a mock object, but using a real object is fine. What can be wrong?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md192',1,'']]],
  ['object_20is_20fine_20what_20can_20be_20wrong_2',['I get a heapcheck failure when using a mock object, but using a real object is fine. What can be wrong?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md192',1,'']]],
  ['object_20is_20invoked_20instead_20what_20s_20the_20problem_3',['When I call a method on my mock object, the method for the real object is invoked instead. What&apos;s the problem?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md185',1,'']]],
  ['object_20needs_20to_20do_20complex_20stuff_20it_20s_20a_20lot_20of_20pain_20to_20specify_20the_20actions_20gmock_20sucks_4',['My mock object needs to do complex stuff. It&apos;s a lot of pain to specify the actions. gMock sucks!',['../md_googletest_2docs_2gmock__faq.html#autotoc_md198',1,'']]],
  ['object_20s_20behavior_20based_20on_20the_20state_5',['Changing a Mock Object&apos;s Behavior Based on the State',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md149',1,'']]],
  ['object_20s_20type_6',['Using the ACTION Object&apos;s Type',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md181',1,'']]],
  ['object_20the_20method_20for_20the_20real_20object_20is_20invoked_20instead_20what_20s_20the_20problem_7',['When I call a method on my mock object, the method for the real object is invoked instead. What&apos;s the problem?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md185',1,'']]],
  ['of_20a_20function_20functor_20or_20callback_8',['Matching the Result of a Function, Functor, or Callback',['../md_googletest_2docs_2reference_2matchers.html#autotoc_md259',1,'']]],
  ['of_20an_20argument_20or_20parameter_20in_20an_20action_9',['Restricting the Type of an Argument or Parameter in an ACTION',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md179',1,'']]],
  ['of_20an_20interface_20satisfy_20some_20common_20requirements_20should_20i_20use_20typed_20tests_20or_20value_20parameterized_20tests_10',['I need to test that different implementations of an interface satisfy some common requirements. Should I use typed tests or value-parameterized tests?',['../md_googletest_2docs_2faq.html#autotoc_md85',1,'']]],
  ['of_20an_20object_11',['Validating a Member of an Object',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md137',1,'']]],
  ['of_20contents_12',['Table of Contents',['../md__r_e_a_d_m_e.html#autotoc_md421',1,'']]],
  ['of_20individual_20tests_20to_20be_20named_20tt_20deathtest_20tt_20when_20it_20uses_20tt_20assert_5fdeath_20tt_13',['Why does GoogleTest require the entire test suite, instead of individual tests, to be named &lt;tt&gt;*DeathTest&lt;/tt&gt; when it uses &lt;tt&gt;ASSERT_DEATH&lt;/tt&gt;?',['../md_googletest_2docs_2faq.html#autotoc_md102',1,'']]],
  ['of_20log_20messages_20what_20do_20i_20do_14',['GoogleTest output is buried in a whole bunch of LOG messages. What do I do?',['../md_googletest_2docs_2faq.html#autotoc_md97',1,'']]],
  ['of_20memory_20when_20compiling_20it_20what_20can_20i_20do_15',['I have a huge mock class, and Microsoft Visual C++ runs out of memory when compiling it. What can I do?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md202',1,'']]],
  ['of_20messages_20is_20it_20a_20gmock_20bug_16',['My program crashed and &lt;tt&gt;ScopedMockLog&lt;/tt&gt; spit out tons of messages. Is it a gMock bug?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md189',1,'']]],
  ['of_20pain_20to_20specify_20the_20actions_20gmock_20sucks_17',['My mock object needs to do complex stuff. It&apos;s a lot of pain to specify the actions. gMock sucks!',['../md_googletest_2docs_2gmock__faq.html#autotoc_md198',1,'']]],
  ['of_20the_20mock_20function_18',['Invoking an Argument of the Mock Function',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md153',1,'']]],
  ['of_20the_20nomenclature_19',['Beware of the Nomenclature',['../md_googletest_2docs_2primer.html#autotoc_md228',1,'']]],
  ['of_20the_20test_20fixture_20or_20setup_20teardown_20',['Should I use the constructor/destructor of the test fixture or SetUp()/TearDown()?',['../md_googletest_2docs_2faq.html#CtorVsSetUp',1,'']]],
  ['of_20the_20tests_21',['Running a Subset of the Tests',['../md_googletest_2docs_2advanced.html#autotoc_md62',1,'']]],
  ['of_20them_20this_20seems_20pretty_20tedious_22',['I have several test suites which share the same test fixture logic; do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_googletest_2docs_2faq.html#autotoc_md96',1,'']]],
  ['ok_20if_20i_20have_20two_20separate_20tt_20test_20foo_20bar_20tt_20test_20methods_20defined_20in_20different_20namespaces_23',['Is it OK if I have two separate &lt;tt&gt;TEST(Foo, Bar)&lt;/tt&gt; test methods defined in different namespaces?',['../md_googletest_2docs_2faq.html#autotoc_md109',1,'']]],
  ['old_20style_20tt_20mock_5fmethodn_20tt_20macros_24',['Old-Style &lt;tt&gt;MOCK_METHODn&lt;/tt&gt; Macros',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md124',1,'']]],
  ['older_20ones_20rule_20makes_20writing_20expectations_20awkward_20why_20does_20gmock_20do_20that_25',['The &quot;newer expectations override older ones&quot; rule makes writing expectations awkward. Why does gMock do that?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md193',1,'']]],
  ['on_26',['My compiler complains that a constructor (or destructor) cannot return a value. What&apos;s going on?',['../md_googletest_2docs_2faq.html#autotoc_md94',1,'']]],
  ['on_20a_20mock_20function_20s_20argument_27',['How can I perform an arbitrary action on a mock function&apos;s argument?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md196',1,'']]],
  ['on_20my_20mock_20object_20the_20method_20for_20the_20real_20object_20is_20invoked_20instead_20what_20s_20the_20problem_28',['When I call a method on my mock object, the method for the real object is invoked instead. What&apos;s the problem?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md185',1,'']]],
  ['on_20subroutines_29',['Asserting on Subroutines',['../md_googletest_2docs_2advanced.html#autotoc_md40',1,'']]],
  ['on_20subroutines_20with_20an_20exception_30',['Asserting on Subroutines with an exception',['../md_googletest_2docs_2advanced.html#autotoc_md39',1,'']]],
  ['on_20the_20arguments_31',['Performing Different Actions Based on the Arguments',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md131',1,'']]],
  ['on_20the_20state_32',['Changing a Mock Object&apos;s Behavior Based on the State',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md149',1,'']]],
  ['on_20using_20gmock_33',['Misc Recipes on Using gMock',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md158',1,'']]],
  ['on_20windows_34',['How do I suppress the memory leak messages on Windows?',['../md_googletest_2docs_2faq.html#autotoc_md106',1,'']]],
  ['on_5fcall_35',['ON_CALL',['../md_googletest_2docs_2reference_2mocking.html#ON_CALL',1,'']]],
  ['on_5fcall_20willbydefault_36',['WillByDefault {#ON_CALL.WillByDefault}',['../md_googletest_2docs_2reference_2mocking.html#autotoc_md273',1,'']]],
  ['on_5fcall_20with_37',['With {#ON_CALL.With}',['../md_googletest_2docs_2reference_2mocking.html#autotoc_md272',1,'']]],
  ['on_5fcall_20would_20it_20be_20reasonable_20not_20to_20show_20the_20warning_20in_20this_20case_38',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md194',1,'']]],
  ['onceaction_39',['OnceAction',['../classtesting_1_1_once_action.html',1,'testing']]],
  ['onceaction_3c_20result_28args_2e_2e_2e_29_3e_40',['OnceAction&lt; Result(Args...)&gt;',['../classtesting_1_1_once_action_3_01_result_07_args_8_8_8_08_4.html',1,'testing']]],
  ['onenvironmentssetupend_20testeventlistener_3a_3aonenvironmentssetupend_41',['OnEnvironmentsSetUpEnd {#TestEventListener::OnEnvironmentsSetUpEnd}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md342',1,'']]],
  ['onenvironmentssetupstart_20testeventlistener_3a_3aonenvironmentssetupstart_42',['OnEnvironmentsSetUpStart {#TestEventListener::OnEnvironmentsSetUpStart}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md341',1,'']]],
  ['onenvironmentsteardownend_20testeventlistener_3a_3aonenvironmentsteardownend_43',['OnEnvironmentsTearDownEnd {#TestEventListener::OnEnvironmentsTearDownEnd}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md349',1,'']]],
  ['onenvironmentsteardownstart_20testeventlistener_3a_3aonenvironmentsteardownstart_44',['OnEnvironmentsTearDownStart {#TestEventListener::OnEnvironmentsTearDownStart}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md348',1,'']]],
  ['ones_20rule_20makes_20writing_20expectations_20awkward_20why_20does_20gmock_20do_20that_45',['The &quot;newer expectations override older ones&quot; rule makes writing expectations awkward. Why does gMock do that?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md193',1,'']]],
  ['oneshotunaryfunctor_46',['OneShotUnaryFunctor',['../structtesting_1_1gmock__more__actions__test_1_1_one_shot_unary_functor.html',1,'testing::gmock_more_actions_test']]],
  ['only_20types_47',['Mocking Methods That Use Move-Only Types',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md159',1,'']]],
  ['only_20types_48',['Legacy workarounds for move-only types',['../md_googletest_2docs_2gmock__cook__book.html#LegacyMoveOnly',1,'']]],
  ['only_20when_20the_20test_20fails_20how_20can_20i_20see_20the_20log_20messages_20when_20the_20death_20test_20succeeds_49',['GoogleTest prints the LOG messages in a death test&apos;s child process only when the test fails. How can I see the LOG messages when the death test succeeds?',['../md_googletest_2docs_2faq.html#autotoc_md104',1,'']]],
  ['ontestend_20testeventlistener_3a_3aontestend_50',['OnTestEnd {#TestEventListener::OnTestEnd}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md346',1,'']]],
  ['ontestiterationend_20testeventlistener_3a_3aontestiterationend_51',['OnTestIterationEnd {#TestEventListener::OnTestIterationEnd}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md350',1,'']]],
  ['ontestiterationstart_20testeventlistener_3a_3aontestiterationstart_52',['OnTestIterationStart {#TestEventListener::OnTestIterationStart}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md340',1,'']]],
  ['ontestpartresult_20testeventlistener_3a_3aontestpartresult_53',['OnTestPartResult {#TestEventListener::OnTestPartResult}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md345',1,'']]],
  ['ontestprogramend_20testeventlistener_3a_3aontestprogramend_54',['OnTestProgramEnd {#TestEventListener::OnTestProgramEnd}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md351',1,'']]],
  ['ontestprogramstart_20testeventlistener_3a_3aontestprogramstart_55',['OnTestProgramStart {#TestEventListener::OnTestProgramStart}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md339',1,'']]],
  ['onteststart_20testeventlistener_3a_3aonteststart_56',['OnTestStart {#TestEventListener::OnTestStart}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md344',1,'']]],
  ['ontestsuiteend_20testeventlistener_3a_3aontestsuiteend_57',['OnTestSuiteEnd {#TestEventListener::OnTestSuiteEnd}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md347',1,'']]],
  ['ontestsuitestart_20testeventlistener_3a_3aontestsuitestart_58',['OnTestSuiteStart {#TestEventListener::OnTestSuiteStart}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md343',1,'']]],
  ['ontheflyprimetable_59',['OnTheFlyPrimeTable',['../class_on_the_fly_prime_table.html',1,'']]],
  ['op_60',['OP',['../tokenizer_8hh.html#acac9cbaeea226ed297804c012dc12b16a7457cdd15d09bfc6c4dbb5d2b6f87390',1,'tokenizer.hh']]],
  ['open_20source_20projects_61',['Related Open Source Projects',['../md_googletest_2_r_e_a_d_m_e.html#autotoc_md418',1,'']]],
  ['operator_20rsquo_20when_20i_20use_20an_20assertion_20what_20gives_62',['The compiler complains about &amp;lsquo;no match for &apos;operator&lt;&lt;&amp;rsquo;` when I use an assertion. What gives?',['../md_googletest_2docs_2faq.html#autotoc_md105',1,'']]],
  ['operator_2a_63',['operator*',['../class_abstract_function.html#a1b48d46fa1ce50817ac24fae683a61bf',1,'AbstractFunction']]],
  ['operator_2b_64',['operator+',['../class_abstract_function.html#a9b4c3b0d6856426f644e8e341b41daad',1,'AbstractFunction']]],
  ['operator_5e_65',['operator^',['../class_abstract_function.html#ac84176f2570111c470d0b9507af06d1c',1,'AbstractFunction::operator^(int power) const'],['../class_abstract_function.html#a51b82e5ad30714a527d353da2c4e6f27',1,'AbstractFunction::operator^(double power) const']]],
  ['operator_7c_66',['operator|',['../class_abstract_function.html#a3f8a0ed6dd14ae2e31ccd3942fe208ef',1,'AbstractFunction']]],
  ['opt_20mode_20is_20this_20a_20googletest_20bug_67',['EXPECT_EQ(htonl(blah), blah_blah) generates weird compiler errors in opt mode. Is this a GoogleTest bug?',['../md_googletest_2docs_2faq.html#autotoc_md87',1,'']]],
  ['options_68',['Running Test Programs: Advanced Options',['../md_googletest_2docs_2advanced.html#autotoc_md59',1,'']]],
  ['or_20c4373_20when_20i_20define_20a_20mock_20method_20with_20a_20const_20parameter_20why_69',['MSVC gives me warning C4301 or C4373 when I define a mock method with a const parameter. Why?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md187',1,'']]],
  ['or_20callback_70',['Matching the Result of a Function, Functor, or Callback',['../md_googletest_2docs_2reference_2matchers.html#autotoc_md259',1,'']]],
  ['or_20destructor_20cannot_20return_20a_20value_20what_20s_20going_20on_71',['My compiler complains that a constructor (or destructor) cannot return a value. What&apos;s going on?',['../md_googletest_2docs_2faq.html#autotoc_md94',1,'']]],
  ['or_20implement_20the_20actioninterface_20interface_72',['I want to define a custom action. Should I use Invoke() or implement the ActionInterface interface?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md200',1,'']]],
  ['or_20lambda_20as_20an_20action_73',['Using a Function, Functor, or Lambda as an Action',['../md_googletest_2docs_2reference_2actions.html#autotoc_md248',1,'']]],
  ['or_20parameter_20in_20an_20action_74',['Restricting the Type of an Argument or Parameter in an ACTION',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md179',1,'']]],
  ['or_20protected_20methods_75',['Mocking Private or Protected Methods',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md120',1,'']]],
  ['or_20seg_20faults_20how_20do_20i_20fix_20it_76',['My death test hangs (or seg-faults). How do I fix it?',['../md_googletest_2docs_2faq.html#autotoc_md91',1,'']]],
  ['or_20setup_20teardown_77',['Should I use the constructor/destructor of the test fixture or SetUp()/TearDown()?',['../md_googletest_2docs_2faq.html#CtorVsSetUp',1,'']]],
  ['or_20value_20parameterized_20tests_78',['I need to test that different implementations of an interface satisfy some common requirements. Should I use typed tests or value-parameterized tests?',['../md_googletest_2docs_2faq.html#autotoc_md85',1,'']]],
  ['order_79',['Expectation Order',['../md_googletest_2docs_2gmock__cheat__sheet.html#autotoc_md113',1,'']]],
  ['ordered_20calls_80',['Ordered Calls',['../md_googletest_2docs_2gmock__for__dummies.html#OrderedCalls',1,'Expecting Ordered Calls'],['../md_googletest_2docs_2gmock__cook__book.html#PartialOrder',1,'Expecting Partially Ordered Calls']]],
  ['ordering_81',['Expectation Ordering',['../md_googletest_2docs_2gmock__for__dummies.html#autotoc_md212',1,'']]],
  ['original_5fworking_5fdir_20unittest_3a_3aoriginal_5fworking_5fdir_82',['original_working_dir {#UnitTest::original_working_dir}',['../md_googletest_2docs_2reference_2testing.html#autotoc_md316',1,'']]],
  ['osstacktracegetter_83',['OsStackTraceGetter',['../classtesting_1_1internal_1_1_os_stack_trace_getter.html',1,'testing::internal']]],
  ['osstacktracegetterinterface_84',['OsStackTraceGetterInterface',['../classtesting_1_1internal_1_1_os_stack_trace_getter_interface.html',1,'testing::internal']]],
  ['otherwise_85',['All Expectations Are Sticky (Unless Said Otherwise)',['../md_googletest_2docs_2gmock__for__dummies.html#StickyExpectations',1,'']]],
  ['ought_20to_20be_20what_20does_20this_20mean_86',['My compiler complains &quot;void value not ignored as it ought to be.&quot; What does this mean?',['../md_googletest_2docs_2faq.html#autotoc_md90',1,'']]],
  ['out_20of_20memory_20when_20compiling_20it_20what_20can_20i_20do_87',['I have a huge mock class, and Microsoft Visual C++ runs out of memory when compiling it. What can I do?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md202',1,'']]],
  ['out_20tons_20of_20messages_20is_20it_20a_20gmock_20bug_88',['My program crashed and &lt;tt&gt;ScopedMockLog&lt;/tt&gt; spit out tons of messages. Is it a gMock bug?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md189',1,'']]],
  ['out_20why_20gmock_20thinks_20my_20expectations_20are_20not_20satisfied_20what_20should_20i_20do_89',['I can&apos;t figure out why gMock thinks my expectations are not satisfied. What should I do?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md188',1,'']]],
  ['outcomes_90',['Test Descriptions, Accuracy Thresholds, and Expected Outcomes',['../md__r_e_a_d_m_e.html#autotoc_md440',1,'']]],
  ['output_91',['Output',['../md_googletest_2docs_2advanced.html#autotoc_md70',1,'Colored Terminal Output'],['../md_googletest_2docs_2advanced.html#autotoc_md69',1,'Controlling Test Output'],['../md_googletest_2docs_2advanced.html#autotoc_md73',1,'Suppressing UTF-8 Text Output']]],
  ['output_20is_20buried_20in_20a_20whole_20bunch_20of_20log_20messages_20what_20do_20i_20do_92',['GoogleTest output is buried in a whole bunch of LOG messages. What do I do?',['../md_googletest_2docs_2faq.html#autotoc_md97',1,'']]],
  ['over_20global_20variables_93',['Why should I prefer test fixtures over global variables?',['../md_googletest_2docs_2faq.html#autotoc_md98',1,'']]],
  ['overloaded_20functions_94',['Selecting Between Overloaded Functions',['../md_googletest_2docs_2gmock__cook__book.html#SelectOverload',1,'']]],
  ['overloaded_20methods_95',['Mocking Overloaded Methods',['../md_googletest_2docs_2gmock__cook__book.html#autotoc_md121',1,'']]],
  ['overloadedmockmethodtest_96',['OverloadedMockMethodTest',['../classtesting_1_1gmock__function__mocker__test_1_1_overloaded_mock_method_test.html',1,'testing::gmock_function_mocker_test']]],
  ['override_20older_20ones_20rule_20makes_20writing_20expectations_20awkward_20why_20does_20gmock_20do_20that_97',['The &quot;newer expectations override older ones&quot; rule makes writing expectations awkward. Why does gMock do that?',['../md_googletest_2docs_2gmock__faq.html#autotoc_md193',1,'']]],
  ['overview_98',['Overview',['../md_googletest_2googlemock_2_r_e_a_d_m_e.html#autotoc_md384',1,'Overview'],['../md__r_e_a_d_m_e.html#autotoc_md423',1,'Project Overview']]],
  ['own_20code_99',['How to become a contributor and submit your own code',['../md_googletest_2_c_o_n_t_r_i_b_u_t_i_n_g.html',1,'']]]
];
